In [2]:
import pandas as pd 
import numpy as np 
import nltk

In [6]:
df=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['labels','messages'])

In [7]:
df

     labels                                           messages
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
df.shape

(5572, 2)

In [9]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
import re
lemmatizer=WordNetLemmatizer()

In [12]:
corpus=[]
for i in range(0,len(df)):
    message=re.sub('[^a-zA-z]',' ',df['messages'][i])
    message=message.lower()
    message=message.split()
    message=[lemmatizer.lemmatize(word,pos='v') for word in message if not word in  stopwords.words('english') ]
    message=' '.join(message)
    corpus.append(message)

In [16]:
y=df['labels']

In [17]:
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: labels, Length: 5572, dtype: object

In [18]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joke wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promise wont take help grant fulfil promise wonderful bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goals team news txt ur national team eg england try wales scotland txt poboxox w wq',
 'seriously spell name',
 'go try months ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'force eat slice really hungry tho suck mark get worry know sick turn pizza lol',
 'lol always convince',
 'catch bus fry egg make tea eat mom leave dinner feel love',
 'back amp pack car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live us',
 'yeah get v apologetic n fall actin like spoil child get catch till go badly cheer',
 'k tell anything',
 'fear faint housework quick cuppa',
 'thank subscription ringtone uk mobile charge month please confirm reply yes reply charge',
 'yup ok go home look timings msg xuhui go learn nd may lesson',
 'oops let know roommate do',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decide anything tomo try invite anything',
 'pls go ahead watts want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg try call reply sms free nokia mobile free camcorder please call delivery tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call message miss call',
 'get hep b immunisation nigeria',
 'fair enough anything go',
 'yeah hopefully tyler could maybe ask around bite',
 'u know stubborn even want go hospital keep tell mark weak sucker hospitals weak suckers',
 'think first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crash place tonight',
 'wow never realize embarassed accomodations think like since best could always seem happy cave sorry give sorry offer sorry room embarassing',
 'sms ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pass call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meet',
 'tell reach',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girls situation seekers',
 'part check iq',
 'sorry roommates take forever ok come',
 'ok lar double check wif da hair dresser already say wun cut v short say cut look nice',
 'value customer please advise follow recent review mob award bonus prize call',
 'today song dedicate day song u dedicate send ur valuable frnds first rply',
 'urgent ur award complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt ls aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finish class',
 'hi babe im home wanna something xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still look job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sms',
 'real u get yo need ticket one jacket do already use multis',
 'yes start send request make pain come back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spend late afternoon casualty mean do stuff moro include time sheet sorry',
 'smile pleasure smile pain smile trouble pour like rain smile sum hurt u smile becoz someone still love see u smile',
 'please call customer service representative pm guarantee cash prize',
 'havent plan buy later check already lido get show e afternoon u finish work already',
 'free ringtone wait collect simply text password mix verify get usher britney fml po box mk h ppw',
 'watch telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bite run forget hairdressers appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x ams xx',
 'still look car buy go drive test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'wow right mean guess give boston men change search location nyc something change cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truly memorable',
 'aight hit get cash',
 'would ip address test consider computer minecraft server',
 'know grumpy old people mom like better lie always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'go dinner msg',
 'ok wif cos like try new things scar u dun like mah cos u say loud',
 'gent try contact last weekend draw show prize guarantee call claim code k valid hrs ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa say happy b day boss felt special askd lunch lunch invite apartment go',
 'winner u specially select receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla need',
 'hmm uncle inform pay school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expire',
 'urgent mobile award bonus caller prize final try contact u call landline box wr c ppm',
 'new address apples pair malarky',
 'todays voda number end select receive award match please call quote claim code standard rat app',
 'go sao mu today do',
 'predict wat time finish buy',
 'good stuff',
 'know yetunde send money yet send text bother send dont involve anything impose anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get lay tonight want real dog locations send direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activities',
 'rcv msgs chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'get c lazy type forget lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt think nver get tire little things lovable persons coz somtimes little things occupy biggest part hearts gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name take class us',
 'freemsg reply text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k delete contact',
 'sindu get job birla soft',
 'wine flow nevering',
 'yup thk cine better cos need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune',
 'everywhere dirt floor windows even shirt sometimes open mouth come flow dream world without half chores time joy lot tv show see guess like things must exist like rain hail mist time do become one',
 'aaooooright work',
 'leave house',
 'hello love get interview today happy good boy think miss',
 'customer service annoncement new years delivery wait please call arrange delivery',
 'winner u specially select receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excite day spend make happy',
 'pls stop bootydelious f invite friend reply yes see www sms ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent try contact last weekend draw show prize guarantee call claim code valid hrs',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure get time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloody hell cant believe forget surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know get money carlos make call',
 'u still go mall',
 'turn friends stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi speak maneesha v like know satisfy experience reply toll free yes',
 'lift hop offer money need especially end month approach hurt study anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'go nothing great bye',
 'hello handsome find job lazy work towards get back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guarantee cash prize',
 'get xmas radio time get',
 'jus reach home go bathe first sis use net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry join league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally complete course',
 'stop however suggest stay someone able give ors every stool',
 'hope settle new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u get persons story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bite bloody babyjontet txt back u xxx',
 'find enc lt gt',
 'send lt gt buck',
 'hello darlin ive finish college txt u finish u love kate xxx',
 'account refill successfully inr lt decimal gt keralacircle prepay account balance rs lt decimal gt transaction id kr lt gt',
 'goodmorning sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa say happy b day boss felt special askd lunch lunch invite apartment go',
 'aight yo dats straight dogg',
 'please give us connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break reward semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match head towards draw prediction',
 'tire sleep well past nights',
 'easy ah sen get select mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bite lor thk e nite scenery nice leh',
 'new mobiles must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lessons happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorry battery die yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight pence',
 'print oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation lose person dont argue ur friends kick amp say always correct',
 'u secret admirer look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeeee tel v avent do sportsx',
 'okay shin mean sign sound better',
 'although tell u dat baig face watch really like e watch u give cos fr u thanx everything dat u do today touch',
 'u remember old commercial',
 'late say website dont slippers',
 'ask call ok',
 'kallis wont bat nd innings',
 'didnt work oh ok goodnight fix ready time wake dearly miss good night sleep',
 'congratulations ur award cd vouchers gift guarantee free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way show deep affection care n luv kettoda manda nice day da',
 '',
 'up days also ship company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect do get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'try contact reply offer video handset anytime network mins unlimited text camcorder reply call',
 'park next mini come today think',
 'yup',
 'anyway go shop cos sis do yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charge pm unsubscribe text stop',
 'dint come us',
 'wana plan trip sometme',
 'sure yet still try get hold',
 'ur ringtone service change free credit go club mobiles com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sort narcotics situation',
 'night end another day morning come special way may smile like sunny ray leave worry blue blue bay',
 'hmv bonus special pound genuine hmv vouchers answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bite',
 'send type food like',
 'do hand celebrations full swing yet',
 'get call tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok ask money far',
 'okie',
 'yeah think usual guy still pass last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friends call world ge',
 'dear shall mail tonite busy street shall update tonite things look ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey tell name gautham ah',
 'haf u find feel stupid da v cam work',
 'oops get bite',
 'much buzy',
 'accidentally delete message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rise grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time get somebody high first time diesel v',
 'shit really shock scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sms ac blind date u rodds aberdeen unite kingdom check http img sms ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hang thread cause u buy stuff',
 'themob check newest selection content game tone gossip babes sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play cs winnersclub po box uz gbp week',
 'say give call friend get money definitely buy end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lose',
 'make day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk get lo oso forget liao',
 'really dude friends afraid',
 'december mobile mths entitle update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bite l cos bus hav gon past cos full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message miss call',
 'hi da todays class',
 'say good sign well know track record read women',
 'cool text park',
 'read text send mean joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany pence per minute call fix line via access number prepayment direct access',
 'chance might evaporate soon violate privacy steal phone number employer paperwork cool please contact report supervisor',
 'valentines day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent win din',
 'sleep surf',
 'sorry call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must texts happy read one wiv hello caroline end favourite bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnite tc practice go',
 'dis yijue jus saw ur mail case huiming havent send u num dis num',
 'one small prestige problem',
 'fancy shag interest sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'check really miss see jeremiah great month',
 'nah help never iphone',
 'car hour half go apeshit',
 'today sorry day ever angry ever misbehave hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay try figure much safely spend weed',
 'lt gt ish minutes minutes ago wtf',
 'thank call forget say happy onam sirji fine remember meet insurance person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratulations ur award cd vouchers gift guarantee free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',
 'actor work work even sleep late since unemployed moment always sleep late unemployed every day saturday',
 'hello get st andrews boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey status right',
 'busy try finish new year look forward finally meet',
 'good afternoon sunshine dawn day refresh happy alive breathe air smile think love always',

In [78]:
y=pd.get_dummies(df['labels'])

## train and test split

In [ ]:
from sklearn.model_selection import train_test_split

In [45]:
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20,random_state=42)

In [46]:
X_train

['reply win weekly fifa world cup hold send stop end service',
 'hello sort town already dont rush home eat nachos let know eta',
 'come guoyang go n tell u tell',
 'hey sathya till dint meet even single time saw situation sathya',
 'orange bring ringtones time chart heroes free hit week go ringtones pics wap stop receive tip reply stop',
 'sit mu wait everyone get suite take shower',
 'finish liao u',
 'urgent mobile award bonus caller prize nd attempt contact call box qu',
 'probably still go stuff',
 'wah lucky man save money hee',
 'hey u still gym',
 'oh lk tt den take e one tt end cine lor dun wan yogasana oso',
 'ok lor',
 'still havent collect dough pls let know go place send get control number',
 'stupid possible',
 'u secret admirer reveal think u r special call opt reply reveal stop per msg recd cust care',
 'amaze rearrange letter give mean dormitory dirty room astronomer moon starer eye see election result lie let recount mother law woman hitler eleven plus two twelve plus one amaze',
 'call listen extreme dirty live chat go office right total privacy one know [sic] listen p min mp',
 'never want tell short edge late',
 'wil reach',
 'oh yeah diet fly window',
 'oh shit think trip loooooool make much sense grin sofa reference sleep couch link send go trip oh babe go celebration rent',
 'send greetings joy happiness gr even',
 'armand say get ass epsilon',
 'aiyah u ok already lar e nydc wheellock',
 'know watch film computer',
 'hear abt tat',
 'oops sorry check mind pick tomo half eight station would ok',
 'anytime lor',
 'friendship poem dear dear u r near hear dont get fear live cheer tear u r always dear gud ni',
 'yar else thk sort funny things',
 'love decision feel could decide love life would much simpler less magical',
 'exact intentions',
 'erm woodland avenue somewhere get parish magazine telephone number',
 'every day use sleep lt gt',
 'jus hope true missin cos really missin do anything feel guilty yet',
 'yup paragon havent decide whether cut yet hee',
 'hmv bonus special pound genuine hmv vouchers answer easy question play send hmv info www percent real com',
 'final chance claim ur worth discount vouchers today text yes savamob member offer mobile cs savamob pobox uz sub',
 'sarcasm nt scarcasim',
 'wherre boytoy',
 'oh mr sheffield wanna play game okay boss nanny give raise give one',
 'prepare pleasured',
 'really sorry b able friday hope u find alternative hope yr term go ok',
 'good morning im suffer fever dysentry able come office today',
 'ur cash balance currently pound maximize ur cash send cash p msg cc po box tcr w',
 'oh forward message think send',
 'k give back thank',
 'tell accenture confirm true',
 'hey want anything buy',
 'date service cal l box sk ch',
 'use foreign stamp whatever send',
 'haha hope hear receipt sound gd luck',
 'chikku nt yet ya free',
 'mu like lt gt second',
 'cant think anyone spare room top head',
 'sex ur mobile free sexy pic jordan text babe every wk get sexy celeb pocketbabe co uk pics wk',
 'today go college able atten class',
 'call freephone',
 'worry finish march ish',
 'lose help',
 'yes good crickiting mind',
 'great',
 'fujitsu series lifebook good',
 'arr birthday today wish get oscar',
 '',
 'gonna say sorry would normal start panic time sorry see tuesday',
 'problem renewal right away dont know detail',
 'bad girl lady',
 'k actually guy meet sunoco howard right way',
 'see prolly yeah',
 'k k special today',
 'u download fring app',
 'wait machan call free',
 'yes completely form clark also utter waste',
 'sorry get late start way',
 'howz pain come today say ystrday ice medicine',
 'hmm shall bring bottle wine keep us amuse joke still bring bottle red white see tomorrow',
 'takin linear algebra today',
 'aww first time u say u miss without ask miss u first love',
 'see see maybe reboot ym see buzz',
 'hi darlin im way london smash another driver big dent im really miss u u xxx',
 'ok lor ned go toa payoh return smth u wan send wat',
 'dear hero leave qatar tonite apt opportunity pls keep touch lt email gt kerala',
 'lol forget eh yes bring babe',
 'someone conacted date service enter phone fancy find call landline pobox n tf',
 'hey get mail',
 'somewhere fredericksburg',
 'watch telugu movie wat abt u',
 'urgent try contact last weekend draw show prize guarantee call claim code k valid hours',
 'reach home finally',
 'love u little pocy bell sorry love u',
 'neft transaction reference number lt gt rs lt decimal gt credit beneficiary account lt gt lt time gt lt gt',
 'dear get lt gt dollars hi hi',
 'ill call u mrw ninish address icky american freek wont stop callin bad jen k eh',
 'go college pa else ill come self pa',
 'u dun drive go sch',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'get smaller capacity one quite ex',
 'bother trust answer pls',
 'men like shorter ladies gaze eye',
 'wan go c doctor',
 'trip ok quite tire lor uni start today ok cos take modules jus concentrate final yr project',
 'get official england poly ringtone colour flag yer mobile tonights game text tone flag optout txt eng stop box w wx',
 'hope settle new school year wishin gr day',
 'friends want drive em someplace probably take',
 'tot u reach liao say shirt',
 'hi move pub would great c u u cud come',
 'appt lt time gt fault u listen tell u twice',
 'network technical support associate',
 'oh ho first time u use type word',
 'wake long ago already dunno thing',
 'moji inform save live thank',
 'text pass collect polyphonic ringtones normal gprs charge apply enjoy tone',
 'call unable cal let meet bhaskar deep',
 'thanx puttin da fone',
 'cool text',
 'ya nice ready thursday',
 'tell number gautham',
 'swhrt u dey hope ur ok tot u day love n miss take care',
 'let know kick',
 'private account statement show unredeemed bonus point claim call identifier code expire',
 'stand',
 'need coz never go',
 'movie theatre go watch unlimited movies pay',
 'ful song lyric',
 'congrats mobile g videophones r call videochat wid ur mat play java game dload polyh music noline rentl bx ip pm',
 'babe lose try reboot',
 'senthil group company apnt pm',
 'dare change ring',
 'yes baby need stretch open pussy',
 'alright sure let know leave',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'cos darren say consider mah ask',
 'leave yet ok lor go elsewhere n eat u thk',
 'need lar jus test e phone card dunno network gd thk wait sis finish bath bathe dun disturb u liao u clean ur room',
 'cool night lemme know around',
 'remember hurt days satanic imposter need pay price may destiny keep go u say pray get mind get',
 'yes sura sun tv lol',
 'latest g still scrounge ammo want give new ak try',
 'part check iq',
 'leave already orchard',
 'battery low babe',
 'tomorrow go theatre come wherever u call tell come tomorrow',
 'get divorce lol',
 'yes meet town cos go gep home could text bus stop worry finish march ish',
 'new address apples pair malarky',
 'draw va dont think',
 'urgent try contact u todays draw show prize guarantee call land line claim j po box c pm',
 'need detail online job',
 'yup anything lor u dun wan ok',
 'bday real april',
 'oooh bed ride ey think',
 'hop get away langport still town tonight',
 'free msg get gnarl barkleys crazy ringtone totally free reply go message right',
 'u find time bus coz need sort stuff',
 'stupid auto correct phone',
 'urgent nd attempt contact u prize yesterday still await collection claim call acl pm',
 'dear deny word please',
 'ur go bahamas callfreefone speak live operator claim either bahamas cruise cash opt txt x',
 'cant pick phone right pls send message',
 'macha dont feel upset assume mindset believe one even wonderful plan us let life begin call anytime',
 'sorry call later',
 'ok',
 'forward please call immediately urgent message wait',
 'u send home first ok lor ready yet',
 'ok lor u wan go look u',
 'really good dhanush rock',
 'oh well c u later',
 'hey leave friday wait ask superior tell',
 'shop till u drop either k k cash travel voucher call ntt po box cr bt fixedline cost ppm mobile vary',
 'well general price lt gt oz let know much want',
 'really dude friends afraid',
 'time come',
 'usf guess might well take car',
 'urgent nd attempt contact u prize yesterday still await collection claim call',
 'seem unnecessarily hostile',
 'send print out da',
 'k sure consent form v',
 'thank vote sing along star karaoke mobile free link reply sing',
 'norm tomorrow finish cos st test need sort library stuff point tomo get letter today access til end march better get move',
 'im snowboard trip wonder plan get everyone together befor go meet greet kind affair cheer',
 'k head mins see',
 'accidentally delete message resend please',
 'yo come carlos soon',
 'nice new shirt thing wear nudist theme _ mu',
 'hurt tease make cry end life die plz keep one rise grave say stupid miss u nice day bslvyl',
 'hear new divorce barbie come ken stuff',
 'one talk',
 'go join tomorrow',
 'hello hun ru way im good date guy meet walkabout far meet soon hows everyone else',
 'dude sux snake get old raiden get buff',
 'sindu get job birla soft',
 'didnt holla',
 'host base idps linux systems',
 'please leave topic sorry tell',
 'yes many sweets',
 'fine thank',
 'please charge mobile get morning',
 'say happen',
 'time n smile r two crucial things life sometimes time make us forget smile sometimes someone smile make us forget time gud noon',
 'spoon okay',
 'bugis oso near wat',
 'make life stressfull always find time laugh may add years life surely add life ur years gud ni swt dream',
 'nothing lor bite bore dun u go home early sleep today',
 'well lot things happen lindsay new years sigh bar ptbo blue heron something go',
 'u get message',
 'happy birthday may ur dream come true',
 'ya tel wats ur problem',
 'r stayin extra week back next wed rugby weekend hi c u soon',
 'thinkin someone good drug',
 'try g decide head',
 'today sunday sunday holiday work',
 'luv u soo much u understand special u r ring u morrow luv u xxx',
 'current lead bid pause auction send customer care',
 'dun wan watch infernal affair',
 'well gonna finish bath good fine night',
 'dont kick coco',
 'diet eat many slice pizza yesterday ugh always diet',
 'fine remember',
 'call message miss call',
 'send jd customer service cum account executive ur mail id detail contact us',
 'ryder unsold gibbs',
 'mean come chase state watch many movies want',
 'sorry call later',
 'buy test yesterday something let know exact day u ovulate get u wks pls pls dont fret know u r worry pls relax also anything ur past history u need tell',
 'ok enjoy r u home',
 'good find way',
 'today system sh get ready well also deep well',
 'think chennai forget come auction',
 'much textin bout',
 'ok ask money far',
 'yavnt try yet never play original either',
 'todays vodafone number end select receive award number match call receive award',
 'havent mus ask u st wat meet lunch den u n meet already lor u wan go ask da ge st confirm w asap',
 'symptoms u love u like listen songs u get stop u see name beloved u get angry',
 'mm food da',
 'hello wats talk email address',
 'ow u dey pay thousad tell u would call',
 'hope feel great pls fill abiola',
 'get call landline number ask come anna nagar go afternoon',
 'lt decimal gt common car better buy china asia find less expensive holla',
 'sunshine hols claim ur med holiday send stamp self address envelope drink us uk po box bray wicklow eire quiz start saturday unsub stop',
 'stop old man get build snowman snow angels snowball fight',
 'u know watchin lido',
 'ok darlin supose ok worry much film stuff mate babysit call xx',
 'urgent mobile number award prize guarantee call land line claim valid hrs ppm',
 'summer finally fancy chat flirt sexy single yr area get match reply summer free join optout txt stop help',
 'also hi wesley',
 'mark work tomorrow get work house meet u afterwards',
 'mmm yummy babe nice jolt suzy',
 'maybe westshore hyde park village place near house',
 'say bad dat e gals know u wat u',
 'see cup coffee animation',
 'ok happen behave like',
 'india go draw series many years south african soil',
 'hi hope good day better night',
 'suck get plan yo valentine yo valentine',
 'urgent costa del sol holiday await collection call toclaim sae tc pobox stockport sk xh cost pm max mins',
 'u guy never invite anywhere',
 'work technical support voice process',
 'spjanuary male sale hot gay chat cheaper call national rate p min cheap p min peak stop texts call p min',
 'yes princess go make moan',
 'good afternoon boytoy go walk day get police abstract still wake miss babe',
 'well know z take care worry',
 'dunno lei like dun haf',
 'bruce amp fowler mom car park long story',
 'hiya stu wot u im much truble home moment evone hat even u wot hell av do wont u tell text bck please luv dan',
 'lookatme thank purchase video clip lookatme charge p think better send video mmsto',
 'chk ur belovd ms dict',
 'dun believe wat',
 'england v macedonia dont miss goals team news txt ur national team eg england try wales scotland txt poboxox w wq',
 'nvm ok',
 'pay lt decimal gt lakhs',
 'easy ah sen get select mean good',
 'aiyah ok wat long get improve already wat',
 'yes post couple pics fb still snow outside wake',
 'multimedia message e mail',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'scotland hope show jjc tendencies take care live dream',
 'derek do class',
 'aight lemme know',
 'yo watch movie netflix',
 'go tell friend sure want live smoke much spend hours beg come smoke',
 'gosh pain spose better come',
 'shall send exe mail id',
 'ok',
 'arrive see couple days lt',
 'u awake snow',
 'sound like plan cardiff still still cold sit radiator',
 'thank lovely wisheds rock',
 'cancer moms make big deal regular checkup aka pap smear',
 'boltblue tone p reply poly mono eg poly cha cha slide yeah slow jamz toxic come stop tone txt',
 'think put back box',
 'hey late amk need drink tea coffee',
 'yes place town meet excite adult single uk txt chat p msg',
 'tire sleep well past nights',
 'unni thank dear recharge rakhesh',
 'k k business',
 'ok knackered come home go sleep good full time work lark',
 'urgent mobile number award prize guarantee call land line claim valid hrs',
 'hey pple nights excellent location wif breakfast hamper',
 'u noe wat time e place dat sell close',
 'free entry gr prize wkly comp chance win latest nokia psp cash every wk txt great http www gr prize com',
 'u make appointment',
 'camera award sipix digital camera call fromm landline delivery within days',
 'look',
 'yup noe leh',
 'yeah probably still gotta check leo',
 'nope juz work',
 'oh fuck juswoke bed boatin dock sleep wid year old spinout giv u da gossip l r xxx',
 'usual iam fine happy amp well',
 'get shitload diamonds though',
 'cutest girl world',
 'gud mrng dear hav nice day',
 'ok dear call chechi',
 'need drug anymore',
 'pay attention',
 'good morning love go sleep wish great day full feel better opportunity last think babe love kiss',
 'work please call',
 'haha awesome might need take doin tonight',
 'like talk pa able dont know',
 'take major roles community outreach rock mel',
 'money steve mate',
 'sound good keep post',
 'anyways go gym whatever love smile hope ok good day babe miss much already',
 'time u get',
 'mystery solve open email send another batch sweetie',
 'hello lover go new job happy think wake slave send tease kiss across sea',
 'someonone know try contact via date service find could call mobile landline box sk ch',
 'rcv msgs chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'ya cant display internal sub gotta extract',
 'todays voda number end select receive award match please call quote claim code standard rat app',
 'drive rain get catch e mrt station lor',
 'yeah go bed back midnight',
 'get ready moan scream',
 'call senthil hsbc',
 'upgrdcentre orange customer may claim free camera phone upgrade loyalty call offer end th july c apply opt available',
 'last chance claim ur worth discount vouchers today text shop savamob offer mobile cs savamob pobox uz sub',
 'hey tmr meet bugis',
 'captain vijaykanth comedy captain tv drunken',
 'still grand prix',
 'aight plan come later tonight',
 'min later k',
 'award sipix digital camera call landline delivery within days cs box bp yr warranty ppm p p',
 'gr see message r u leave congrats dear school wat r ur plan',
 'yup',
 'ok much though h friday cant wait dunno wot hell im gonna another weeks become slob oh wait already do',
 'dont know bring food',
 'dont want hear philosophy say happen',
 'get call landline number ask come anna nagar go afternoon',
 'tell friend come round til like lt gt ish',
 'dun need pick ur gf',
 'look addie go back monday suck',
 'hanks lotsly',
 'pls dont play others life',
 'sir wait call free please call',
 'depend individual lor e hair dresser say pretty parent say look gong u kaypoh also dunno wat collect',
 'ok come home',
 'r u say order slippers cos pay return',
 'hungry gay guy feel hungry call p min stop texts call p min',
 'accidentally bring em home box',
 'wait bus stop aft ur lect lar dun c go get car come back n pick',
 'tot group mate lucky havent reply wat time need leave',
 'nobody name penis girls name story add',
 'pls need dat slowly vomit',
 'nice wait texting right gonna pay ticket ya know',
 'sorry join league people dont keep touch mean great deal friend time even great personal cost great week',
 'yeah open chat click friend list make list easy pie',
 'cool last little get time soon',
 'oops thk dun haf enuff go check tell',
 'know shall speak lt gt minutes',
 'hey anyway',
 'darren say dat u meet da ge den dun meet dinner cos later u leave xy feel awkward den u meet lunch lor',
 'buy today need c meh',
 'hi get money da',
 'pick pm go taunton still want come',
 'great church holla get',
 'many things antibiotic use chest abdomen gynae infections even bone infections',
 'da birthdate certificate april real date today dont publish shall give special treat keep secret way thank wish',
 'cmon babe make horny turn txt fantasy babe im hot sticky need reply cost cancel send stop',
 'tel software name',
 'better bb wont use wife doctor',
 'hello madam',
 'happen interview',
 'yeah imma come cause jay want drug',
 'discount code rp stop message reply stop www regalportfolio co uk customer service',
 'pls ask macho much budget bb bold cos saw new one lt gt dollars',
 'say text one time',
 'win winner mr foley ipod excite prize soon keep eye ur mobile visit www win co uk',
 'jesus christ bitch try give drug answer fuck phone',
 'stayin trouble stranger saw dave day sort still bloke u gona get girl mr ur mum still think get getha',
 'tessy pls favor pls convey birthday wish nimya pls dnt forget today birthday shijas',
 'probably lt gt',
 'unique enough find th august www areyouunique co uk',
 'either way work lt gt years old hope doesnt bother',
 'would ip address test consider computer minecraft server',
 'oops lt gt',
 'thts god gift bird humans hav natural gift frm god',
 'reverse cheat mathematics',
 'lt gt pple marry lovers becz hav gud undrstndng dat avoid problems send dis u u wil get gud news friday person like tomorrow best day life dont break chain break suffer send lt gt frnds lt gt mins whn u read',
 'little difficult simple way enter place',
 'u',
 'hi elaine today meet confirm',
 'onum ela pa normal',
 'two cartons u please shelve',
 'mean february april get place stay hustle back forth audition season since sister move away harlem',
 'ok theory test go book think may coz think wanna go jiayin isnt free',
 'ok gonna head usf like fifteen minutes',
 'texted finish long time ago shower er ything',
 'freemsg hi baby wow get new cam moby wanna c hot pic fancy chat im w utxt rply chat hlp msg p rcv',
 'yes last practice',

In [47]:
y_train

       spam
1978   True
3989  False
3935  False
4078  False
4086   True
...     ...
3772  False
5191  False
5226  False
5390  False
860   False

[4457 rows x 1 columns]

In [48]:
X_test

['squeeeeeze christmas hug u lik frndshp den hug back u get u r cute u r luvd u r lucky none people hate u',
 'also sorta blow couple time recently id rather text blue look weed',
 'mmm thats better get roast b better drink good indian',
 'mm kanji dont eat anything heavy ok',
 'ring come guy costume gift future yowifes hint hint',
 'sary need tim bollox hurt lot tol',
 'love decision feel could decide love life would much simpler less magical',
 'supervisor find one lor thk students havent ask yet tell u aft ask',
 'dear good morning',
 'chennai velachery',
 'lol grr mom take forever prescription pharmacy like minutes away ugh',
 'valentines huh proof fb page ugh glad really watch rupaul show tool',
 'wif buy tix lar',
 'er hello things quite go plan limp slowly home follow aa exhaust hang',
 'free ringtone text first poly text get true tone help st free tone x pw e nd txt stop',
 'sir wait call',
 'crazy ar marry like gd look guy frens like say korean leona fave dun thk aft think mayb prob go',
 'hey free call',
 'fight world easy u either win lose bt fightng close u dificult u lose u lose u win u still lose',
 'u go back urself lor',
 'yeah leave couple minutes amp let know get mu',
 'customer place call',
 'err cud go pm get way contact',
 'guess worry must know way body repair quite sure worry take slow first test guide ovulation relax nothing say reason worry keep followin',
 'nd time try contact u u pound prize claim easy call p per minute bt national rate',
 'k k congratulation',
 'still look job much ta earn',
 'gud gud k chikku tke care sleep well gud nyt',
 'give time walk',
 'wat',
 'nothing u dinner w us',
 'thanx yup come back sun finish dinner go back hotel time fly tog exactly mth today hope haf many mths come',
 'xy go e lunch',
 'pls send company name saibaba colany',
 'ur change da report big cos already make change da previous report',
 'morning ok',
 'yeah jus rite',
 'never lei v lazy get wat dat day send da url cant work one',
 'aight head',
 'prefer free days tues wed fri oso ask workin lor',
 'reminder download content already pay goto http doit mymoby tv collect content',
 'jus finish blow hair u finish dinner already',
 'pay like lt gt yrs difficult',
 'hello boytoy geeee miss today like send tm remind think love love kiss',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'anything lor',
 'text creepy like think forget',
 'guess somebody know secretly fancy wanna find give us call landline datebox essexcm xn p min',
 'like jerk',
 'office whats matter msg call break',
 'best watch say cause get drink motherfucker',
 'free st week nokia tone ur mob every week txt nokia get txting tell ur mat www getzed co uk pobox w wq norm p tone',
 'hey das cool iknow wellda peril studentfinancial crisis spk u l r',
 'nah help never iphone',
 'ok',
 'even friend priest call',
 'oh gei happend tron maybe ill dl',
 'see miss call dear brother gr day',
 'free day finish mon n thurs',
 'good even sir hope nice day want bring notice late pay rent past months pay lt gt charge felt would inconsiderate nag something give great cost didnt speak however recession wont able pay charge month hence askin well ahead month end please help thank everything',
 'urgent mobile number award prize guarantee call land line claim valid hrs ppm',
 'wat time r go xin hostel',
 'message free welcome new improve sex dog club unsubscribe service reply stop msgs p',
 'hi hope u get txt journey hasnt gd mins late think',
 'bill letter expect one orange bill may still say orange',
 'annoy',
 'go project centre',
 'roger probably go rem',
 'lol know awesome phone could click delete right want',
 'height oh shit situation guy throw luv letter gal fall brothers head whos gay',
 'sms service inclusive text credit pls goto www comuk net login qxj unsubscribe stop extra charge help comuk cm ae',
 'make day great day',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'todays voda number end select receive award hava match please call quote claim code standard rat app',
 'oh god find number glad text back xafter msgs cst std ntwk chg',
 'winner value network customer select receivea prize reward claim call claim code kl valid hours',
 'still around look pick later',
 'neft transaction reference number lt gt rs lt decimal gt credit beneficiary account lt gt lt time gt lt gt',
 'ok take ur time n enjoy ur dinner',
 'hey cutie go wales kinda ok like hill shit still avent kill',
 'thank love rock',
 'reach already',
 'home',
 'also piece',
 'next amaze xxx picsfree video send enjoy one vid enough day text back keyword picsfree get next video',
 'quite ok bite ex u better go eat smth else feel guilty',
 'dude get haircut breezy',
 'actually fuck whatever find excuse tampa point january though',
 'management puzzeles',
 'hey whats plan sit',
 'fear faint housework quick cuppa',
 'oh ho first time u use type word',
 'aiyar u poor thing give u support k jia think u',
 'get fujitsu ibm hp toshiba get lot model say',
 'prepare pound every night',
 'yeah like go like friends imma flip shit like half hour',
 'wow healthy old airport rd lor cant thk anything else b bath dog later',
 'dai lt gt naal eruku',
 'ask around lot term mids',
 'u reckon need arrange transport u thank',
 'yes fine',
 'wait inside da car park',
 'dear get train seat mine lower seat',
 'th gower mate r u man good wales ill b back morrow c u wk msg random',
 'edison rightly say fool ask question wise man answer know us speechless viva gm gn ge gnt',
 'r u still work',
 'yeah sure thing mate haunt get stuff sort im go sound anyway promote hex way dont know number joke',
 'amaze quote sometimes life difficult decide whats wrong lie bring smile truth bring tear',
 'ok ok ok whats ur todays plan',
 'sleep nt feel well',
 'hiya comin bristol st week april les get rudi new yrs eve snore drink u bak college yet work send ink bath',
 'go write ccna exam week',
 'well might come',
 'dear shall mail tonite busy street shall update tonite things look ok varunnathu edukkukayee raksha ollu good one real sense',
 'height confidence aeronautics professors wer calld amp wer askd sit aeroplane aftr sit wer tell dat plane ws make students dey hurry plane bt didnt move say make students wont even start datz confidence',
 'december mobile mths entitle update latest colour camera mobile free call mobile update co free',
 'account refill successfully inr lt decimal gt keralacircle prepay account balance rs lt decimal gt transaction id kr lt gt',
 'oh half hour much longer syria canada eh wow must get much work do day us extra time grin',
 'lmao take pic send',
 'rock yr chik get filthy film xxx pics yr phone rply filth saristar ltd e yt p per days stop cancel',
 'watch live',
 'sir need velusamy sir date birth company bank facilities detail',
 'anything lar',
 'cool text head',
 'know thinkin malaria relax children cant handle malaria would worse gastroenteritis take enough replace loss temp reduce give malaria meds vomit self limit illness mean days completely stop',
 'yo chad gymnastics class wanna take site say christians class full',
 'sure get acknowledgement astoundingly tactless generally faggy demand blood oath fo',
 'hi test lt gt rd',
 'house maid murderer coz man murder lt gt th january public holiday govt instituitions close include post office',
 'sms auction brand new nokia auction today auction free join take part txt nokia',
 'yeah usual guy town definitely people around know',
 'babe miiiiiiissssssssss need crave geeee sad without babe love',
 'happy new year man',
 'hey thk juz go accordin wat discuss yest lor except kb sun cos nt much lesson go attend kb sit',
 'take half day leave bec well',
 'maybe fat finger press button know',
 'babe go day miss already love love kiss hope everything go well',
 'black shirt n blue jeans thk c',
 'gudnite tc practice go',
 'worry hope photo shoot go well spiffing fun workage',
 'nt drive even many reason call bbd thts chikku hw abt dvg cold hear tht vinobanagar violence hw condition hw ru problem',
 'mom want know',
 'good good job like entrepreneurs',
 'get tv watch meh u work today',
 'pls pls send mail know relatives come deliver know cost risk benefit anything else thank',
 'might want pull case plan spend much confidence derek taylor money management',
 'private account statement show unredeemed bonus point claim call identifier code expire',
 'sad puppy noise',
 'oclock mine bash flat plan',
 'watch movie already xy want shop shop w',
 'thats cool princess cover face hot sticky cum',
 'unfortunately find pick sister airport even think go try go one th',
 'beautiful tomorrow never come come already today hunt beautiful tomorrow waste wonderful today goodmorning',
 'pussy perfect',
 'medical missions nigeria',
 'wot wed nite til',
 'number u live',
 'yeah impression get',
 'hi darlin finish u pick meet text back number luv kate xxx',
 'eldest know',
 'babe u want dont u baby im nasty thing filthyguys fancy rude time sexy bitch go slo n hard txt xxx slo msgs',
 'cause old live high',
 'da vijay go talk jaya tv',
 'anybody number still think tactful way ask alex',
 'sorry able get see morning',
 'ok take care umma',
 'want cock hubby away need real man satisfy txt wife string action txt stop end txt rec ea otbox la ws',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'help u swoop pick u wherever ur bird r meet u want',
 'people tour think sofa thing send curious sugar',
 'join today',
 'come lt n pass lar',
 'ready call',
 'da happy sit together na',
 'wa u efficient gee thanx',
 'short cute good person dont try prove gud mrng',
 'idea guess work hour suppose leave since usual nobody interest figure shit last second',
 'hello love go day wish well fine babe hope find job prospect miss boytoy tease kiss',
 'im late tellmiss im way',
 'yup next stop',
 'dont thnk wrong call us',
 'hey loverboy love tell look picture ache feel legs fuck want need crave',
 'love aathi love u lot',
 'im do studyn library',
 'oh howda gud gud mathe en samachara chikku',
 'send ur birthdate month year tel u ur life partner name method calculation reply must',
 'good even',
 'many time lose best ones bcoz',
 'hi frnd best way avoid missunderstding wit beloved one',
 'happy new years melody',
 'jay say double faggot',
 'pick rayan macleran',
 'thats go ruin thesis',
 'meet lobby',
 'hello go village pub either come accordingly ok',
 'ok wont call disturb one know avoid burden',
 'oh icic k lor den meet day',
 'sir late pay rent past months pay lt gt charge felt would inconsiderate nag something give great cost didnt speak however recession wont able pay charge month hence askin well ahead month end please help thank',
 'dai download exe file run exe instal',
 'sorry call later',
 'night end another day morning come special way may smile like sunny ray leave worry blue blue bay gud mrng',
 'posible dnt live lt gt century cm frwd n thnk different',
 'think rule tamilnadu tough people',
 'sorry brah finish last exams',
 'know wot people wear shirt jumpers hat belt know r cribbs',
 'ok ok guess',
 'sorry call later',
 'talk',
 'free entry weekly competition text word win c www txttowin co uk',
 'worse use half way stop better complete',
 'somebody go andros steal ice',
 'urgent please call landline cash holiday await collection cs sae po box xy',
 'u noe send file computers',
 'hmm well night night',
 'finally come fix ceiling',
 'affidavit say lt gt e twiggs st division g courtroom lt gt lt time gt double check text tomorrow',
 'go bath msg next lt gt min',
 'wait come lt gt min',
 'al moan n e thin go wrong fault al de arguments r fault feed himso bother hav go thanx xx',
 'something u eat',
 'wake gt',
 'congratulations thank good friend u xmas prize claim easy call p per minute bt national rate',
 'work ah den plus lor u workin oso rite den go orchard lor place go liao',
 'sos amount get pls',
 'walk hour c u show care wont u believe im serious',
 'reason team budget available last buy unsold players base rate',
 'dont file bag work call tell find anything room',
 'dear call tmorrow pls accomodate',
 'go ride bike',
 'pls speak wont ask anything friendship',
 'sorry call later',
 'k k also fine complete course',
 'k ill drink pa need srs model pls send mail id pa',
 'get chicken broth want ramen unless know',
 'hello darling today would love chat dont tell look like sexy',
 'unless situation go gurl would appropriate',
 'freemsg txt call claim reward hours talk time use phone subscribe gbp mnth inc hrs stop txtstop',
 'well weather cali great complexities great need car move freely tax outrageous great place sad part miss home',
 'urgent try contact u todays draw show prize guarantee call land line claim valid hrs',
 'tire argue week week want',
 'congrats mobile g videophones r call videochat wid ur mat play java game dload polyph music noline rentl bx ip p',
 'yo parent gettin cash good news pick downstem',
 'party alex nichols',
 'camera award sipix digital camera call fromm landline delivery within days',
 'usual u call ard smth',
 'nope drivin neva develop da photos lei',
 'hungry',
 'fine send greetings',
 'havent shop lor juz arrive',
 'ill lt gt ok',
 'good morning repair shop reason hour',
 'urgent try contact last weekend draw show prize guarantee call claim code valid hrs',
 'wet right',
 'dear angry busy dear',
 'call see facebook huh',
 'good sleep rhythm person establish rhythm body learn use want know',
 'come get b quite diff guess rite',
 'nothing jus tot u would ask cos u ba gua go mt faber yest yest jus go already mah today go jus call lor',
 'come friday leave pongal get news work place',
 'someone contact date service enter phone fancy find call landline pobox n tf p',
 'guess somebody know secretly fancy wanna find give us call landline datebox essexcm xn p min',
 'number gonna massive pain ass rather get involve possible',
 'lor change suntec wat time u come',
 'wonder world th th ur style th ur smile th ur personality rd ur nature nd ur sms st ur lovely friendship good morning dear',
 'somewhere beneath pale moon light someone think u dream come true goodnite amp sweet dream',
 'sorry call later meet',
 'right make appointment right',
 'love',
 'dare ask luck sort car',
 'take care financial problem help',
 'get dump heap mom decide come low bore',
 'new years eve ok go party boyfriend si hey',
 'realize years thousands old ladies run around tattoo',
 'nutter cutter ctter cttergg cttargg ctargg ctagg ie',
 'thank tescos quite nice go speak soon',
 '',
 'r go today meet',
 'ex wife able kid want kid one day',
 'oh ok didnt know mean yep baby jontin',
 'send type food like',
 'want get lay tonight want real dog locations send direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'dnt worry use ice piece cloth pack also take tablets',
 'hi darlin hope nice night wish come cant wait see love fran ps want dirty anal sex want man gang bang',
 'cuz ibored wanna study',
 'adult would learn experience real danger dont like peep use drug dont need comment',
 'ok c',
 'hi u decide wot get bday ill prob jus get voucher frm virgin sumfing',
 'fantasy football back tv go sky gamestar sky active play k dream team score start saturday register sky opt',
 'today workin free oso gee thgt u workin ur fren shop',
 'slaaaaave must summon time wish come anymore',
 'im gonna miss u much',
 'ur tonexs subscription renew charge choose polys month www clubzed co uk bill msg',
 'hear u call rude chat private line cum wan c pics gettin shag text pix end send stop sam xxx',
 'av new number wil u use one ta',
 'wat r u',
 'dude ive see lotta corvettes lately',
 'promise take good care princess run please send pics get chance ttyl',
 'sppok ur mob halloween collection nokia logo pic message plus free eerie tone txt card spook',
 'wonder would okay call uncle john let know things nigeria r lt gt dollars years send know strain plan pay back every dime give every dime expect anything practical something like',
 'urgent mobile award bonus caller prize final try contact u call landline box wr c ppm',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'master buy bb cos sale bf',
 'lul im gettin juicy gossip hospital two nurse talk fat gettin one think shes obese oyea',
 'actually delete old website blogging magicalsongs blogspot com',
 'castor need see something',
 'think king hill thing',
 'ya srsly better yi tho',
 'call germany pence per minute call fix line via access number prepayment direct access',
 'superb think grateful u dont everything u want mean u still opportunity happier tomorrow u today',
 'sit right okay thank',
 'always chat fact need money raise',
 'hey sweet wonder moment might come want send file someone go yahoo connection suck remember set page go download format disc could tell know way download big file download stuff directly internet help would great prey tease kiss',
 'necessarily respectful',
 'moji love word rich day',
 'thank ringtone order reference number x mobile charge tone arrive please call customer service',
 'think steyn surely get one wicket',
 'phone weirdest auto correct',
 'get wat buy tell us need come',
 'course make stink',
 'oh god almost home',
 'home work meh',
 'hey congrats u id luv ive go home',
 'late',
 'dude u knw also telugu thts gud k gud nyt',
 'bloomberg message center wait apply future http career bloomberg com',
 'ok try week end course coimbatore',
 'u secret admirer look make contact u find r reveal think ur special call',
 'lil fever fine',
 'say quit least time day wudn take much notice nah mind gonna see want come taunton tonight u tell',
 'like personal size',
 'lara say loan lt gt',
 'water log desert geoenvironmental implications',
 'want inside every night',
 'argh fuck nobody town _',
 'try make another butt',
 'ugh fuck resubbing eve',
 'come people',
 'funny fact nobody teach volcanoes erupt tsunamis arise hurricanes sway aroundn teach hw choose wife natural disasters happen',
 'well do costa del sol holiday await collection call toclaim sae tcs pobox stockport sk xh cost pm max mins',
 'fuck cedar key fuck come anyway tho',
 'see swing bite get things take care firsg',
 'r u scratch',
 'start dont stop pray good ideas anything see help guy forward link',
 'join today formally pls keep pray talk later',
 'xmas reward wait computer randomly pick loyal mobile customers receive reward call',
 'gr see message r u leave congrats dear school wat r ur plan',
 'omg want scream weigh lose weight woohoo',
 'yo dude guess get arrest day',
 'dunno cos v late n reach inside already eat spageddies lor e gals r laugh lor',
 'like new house',
 'haha kid papa need drug',
 'aight yo dats straight dogg',
 'mum hope great day hop text meet well full life great day abiola',
 'lose kilos today',
 'oh god take teeth pain',
 'kallis wont bat nd innings',
 'princess bet brothas chase',
 'important customer service announcement call freephone',
 'actually decide hungry leave yet v',
 'please inform application airtel broadband process successfully installation happen within days',
 'si como listen plaid album quite gd new air hilarious also buy braindance comp ofstuff aphex abel u hav hear c u sn xxxx',
 'omg one thing another cat worm bad day end',
 'say right giggle saw u would possibly first person die nvq think much could',
 'ok come ur home half hour',
 'seem like weird time night g want come smoke day shitstorm attribute always come make everyone smoke',
 'fr ndship like needle clock though v r clock v r nt able meet evn v meet itz second bt v alwys stay conected gud',
 'k k detail want transfer acc enough',
 'aldrine rakhesh ex rtm pls call urgent',
 'unbelievable faglord',
 'plan usually stop find hella weed smoke hella weed',
 'still look car buy go drive test yet',

In [49]:
y_test

       spam
3245  False
944   False
1044  False
2484  False
812   False
...     ...
4264  False
2439  False
5556  False
4205  False
4293  False

[1115 rows x 1 columns]

# feature engineering

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
cv=CountVectorizer(max_features=2000,ngram_range=(1,2))

In [52]:
X_train=cv.fit_transform(X_train)

In [53]:
X_test=cv.transform(X_test)

## model training

In [55]:
from sklearn.naive_bayes import MultinomialNB

In [56]:
NB=MultinomialNB()

In [57]:
model=NB.fit(X_train,y_train)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [58]:
y_pred=model.predict(X_test)

In [59]:
from sklearn.metrics import accuracy_score

In [60]:
accuracy_score(y_test,y_pred)

0.9847533632286996

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       966
        True       0.95      0.93      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115

# TD-IDF

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [63]:
tf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [64]:
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20,random_state=42)

In [68]:
len(X_train)

4457

In [67]:
len(X_test)

1115

In [71]:
y_train.shape,y_test.shape

((4457, 1), (1115, 1))

In [72]:
y_train

       spam
1978   True
3989  False
3935  False
4078  False
4086   True
...     ...
3772  False
5191  False
5226  False
5390  False
860   False

[4457 rows x 1 columns]

In [73]:
y_test

       spam
3245  False
944   False
1044  False
2484  False
812   False
...     ...
4264  False
2439  False
5556  False
4205  False
4293  False

[1115 rows x 1 columns]

In [74]:
X_train=tf.fit_transform(X_train)
X_test=tf.transform(X_test)

In [75]:
model=NB.fit(X_train,y_train)

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [76]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_test,y_pred)

0.9847533632286996

In [77]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       966
        True       0.95      0.93      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115