In [10]:
import pandas as pd 
import numpy as np 
import nltk 
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [2]:
!pip install gensim

Requirement already satisfied: gensim in c:\users\hp\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\hp\anaconda3\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in c:\users\hp\anaconda3\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\hp\anaconda3\lib\site-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in c:\users\hp\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [5]:
df=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [6]:
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
lemmatizer=WordNetLemmatizer()

In [39]:
corpus=[]
for i in range(0,len(df)):
    message=re.sub('[^a-zA-z]',' ',df['message'][i])
    message=message.lower()
    message=message.split()
    message=[lemmatizer.lemmatize(word,pos='v') for word in message  ]
    message=' '.join(message)
    corpus.append(message)

In [40]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there get amore wat',
 'ok lar joke wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he live around here though',
 'freemsg hey there darling it s be week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother be not like to speak with me they treat me like aid patent',
 'as per your request melle melle oru minnaminunginte nurungu vettam have be set as your callertune for all callers press to copy your friends callertune',
 'winner as a value network customer you have be select to receivea prize reward to claim call claim code kl valid hours only',
 'have your mobile months or more u r entitle to update to the latest colour mobiles with camera for free call the mobile update co free on',
 'i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cry enough today',
 'six chance to win cash from to pound txt csh and send to cost p day days tsandcs apply reply hl info',
 'urgent you have win a week free membership in our prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw',
 'i ve be search for the right word to thank you for this breather i promise i wont take your help for grant and will fulfil my promise you have be wonderful and a bless at all time',
 'i have a date on sunday with will',
 'xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k i m watch here',
 'eh u remember how spell his name yes i do he v naughty make until i v wet',
 'fine if that s the way u feel that s the way its gota b',
 'england v macedonia dont miss the goals team news txt ur national team to eg england to try wales scotland txt poboxox w wq',
 'be that seriously how you spell his name',
 'i m go to try for months ha ha only joke',
 'so pay first lar then when be da stock comin',
 'aft i finish my lunch then i go str down lor ard smth lor u finish ur lunch already',
 'ffffffffff alright no way i can meet up with you sooner',
 'just force myself to eat a slice i m really not hungry tho this suck mark be get worry he know i m sick when i turn down pizza lol',
 'lol your always so convince',
 'do you catch the bus be you fry an egg do you make a tea be you eat your mom s leave over dinner do you feel my love',
 'i m back amp we re pack the car now i ll let you know if there s room',
 'ahhh work i vaguely remember that what do it feel like lol',
 'wait that s still not all that clear be you not sure about me be sarcastic or that that s why x doesn t want to live with us',
 'yeah he get in at and be v apologetic n have fall out and she be actin like spoil child and he get catch up in that till but we win t go there not do too badly cheer you',
 'k tell me anything about you',
 'for fear of faint with the of all that housework you just do quick have a cuppa',
 'thank for your subscription to ringtone uk your mobile will be charge month please confirm by reply yes or no if you reply no you will not be charge',
 'yup ok i go home look at the timings then i msg again xuhui go to learn on nd may too but her lesson be at be',
 'oops i ll let you know when my roommate s do',
 'i see the letter b on my car',
 'anything lor u decide',
 'hello how s you and how do saturday go i be just texting to see if you d decide to do anything tomo not that i m try to invite myself or anything',
 'pls go ahead with watts i just want to be sure do have a great weekend abiola',
 'do i forget to tell you i want you i need you i crave you but most of all i love you my sweet arabian steed mmmmmm yummy',
 'rodger burn msg we try to call you re your reply to our sms for a free nokia mobile free camcorder please call now for delivery tomorrow',
 'who be you see',
 'great i hope you like your man well endow i be lt gt inch',
 'no call message miss call',
 'didn t you get hep b immunisation in nigeria',
 'fair enough anything go on',
 'yeah hopefully if tyler can t do it i could maybe ask around a bite',
 'u don t know how stubborn i be i didn t even want to go to the hospital i keep tell mark i m not a weak sucker hospitals be for weak suckers',
 'what you think about me first time you saw me in class',
 'a gram usually run like lt gt a half eighth be smarter though and get you almost a whole second gram for lt gt',
 'k fyi x have a ride early tomorrow morning but he s crash at our place tonight',
 'wow i never realize that you be so embarassed by your accomodations i think you like it since i be do the best i could and you always seem so happy about the cave i m sorry i didn t and don t have more to give i m sorry i offer i m sorry your room be so embarassing',
 'sms ac sptv the new jersey devil and the detroit red wing play ice hockey correct or incorrect end reply end sptv',
 'do you know what mallika sherawat do yesterday find out now lt url gt',
 'congrats year special cinema pass for be yours call now c suprman v matrix starwars etc all free bx ip we pm dont miss out',
 'sorry i ll call later in meet',
 'tell where you reach',
 'yes gauti and sehwag out of odi series',
 'your gonna have to pick up a burger for yourself on your way home i can t even move pain be kill me',
 'ha ha ha good joke girls be situation seekers',
 'its a part of check iq',
 'sorry my roommates take forever it ok if i come by now',
 'ok lar i double check wif da hair dresser already he say wun cut v short he say will cut until i look nice',
 'as a value customer i be please to advise you that follow recent review of your mob no you be award with a bonus prize call',
 'today be song dedicate day which song will u dedicate for me send this to all ur valuable frnds but first rply me',
 'urgent ur award a complimentary trip to eurodisinc trav aco entry or to claim txt dis to morefrmmob shracomorsglsuplt ls aj',
 'do you hear about the new divorce barbie it come with all of ken s stuff',
 'i plane to give on this month end',
 'wah lucky man then can save money hee',
 'finish class where be you',
 'hi babe im at home now wanna do something xx',
 'k k where be you how do you perform',
 'u can call me now',
 'i be wait machan call me once you free',
 'thats cool i be a gentleman and will treat you with dignity and respect',
 'i like you people very much but be very shy pa',
 'do not operate after lt gt or what',
 'its not the same here still look for a job how much do ta s earn there',
 'sorry i ll call later',
 'k do you call me just now ah',
 'ok i be on the way to home hi hi',
 'you will be in the place of that man',
 'yup next stop',
 'i call you later don t have network if urgnt sms me',
 'for real when u get on yo i only need more ticket and one more jacket and i m do i already use all my multis',
 'yes i start to send request to make it but pain come back so i m back in bed double coin at the factory too i gotta cash in all my nitros',
 'i m really not up to it still tonight babe',
 'ela kano il download come wen ur free',
 'yeah do don t stand to close tho you ll catch something',
 'sorry to be a pain be it ok if we meet another night i spend late afternoon in casualty and that mean i haven t do any of y stuff moro and that include all my time sheet and that sorry',
 'smile in pleasure smile in pain smile when trouble pour like rain smile when sum hurt u smile becoz someone still love to see u smile',
 'please call our customer service representative on between be pm as you have win a guarantee cash or prize',
 'havent plan to buy later i check already lido only get show in e afternoon u finish work already',
 'your free ringtone be wait to be collect simply text the password mix to to verify get usher and britney fml po box mk h ppw',
 'watch telugu movie wat abt u',
 'i see when we finish we have load of loan to pay',
 'hi wk be ok on hols now yes on for a bite of a run forget that i have hairdressers appointment at four so need to get home n shower beforehand do that cause prob for u',
 'i see a cup of coffee animation',
 'please don t text me anymore i have nothing else to say',
 'okay name ur price as long as its legal wen can i pick them up y u ave x ams xx',
 'i m still look for a car to buy and have not go the drive test yet',
 'as per your request melle melle oru minnaminunginte nurungu vettam have be set as your callertune for all callers press to copy your friends callertune',
 'wow you re right i didn t mean to do that i guess once i give up on boston men and change my search location to nyc something change cuz on my signin page it still say boston',
 'umma my life and vava umma love you lot dear',
 'thank a lot for your wish on my birthday thank you for make my birthday truly memorable',
 'aight i ll hit you up when i get some cash',
 'how would my ip address test that consider my computer isn t a minecraft server',
 'i know grumpy old people my mom be like you better not be lie then again i be always the one to play joke',
 'dont worry i guess he s busy',
 'what be the plural of the noun research',
 'go for dinner msg you after',
 'i m ok wif it cos i like try new things but i scar u dun like mah cos u say not too loud',
 'gent we be try to contact you last weekend draw show that you win a prize guarantee call claim code k valid hrs only ppm',
 'wa ur openin sentence very formal anyway i m fine too juz tt i m eatin too much n puttin on weight haha so anythin special happen',
 'as i enter my cabin my pa say happy b day boss i felt special she askd me lunch after lunch she invite me to her apartment we go there',
 'you be a winner u have be specially select receive or a holiday flight inc speak to a live operator claim p min',
 'goodo yes we must speak friday egg potato ratio for tortilla need',
 'hmm my uncle just inform me that he s pay the school directly so pls buy food',
 'private your account statement for show unredeemed bonus point to claim call identifier code expire',
 'urgent your mobile no be award bonus caller prize on this be our final try to contact u call from landline box wr c ppm',
 'here be my new address apples pair all that malarky',
 'todays voda number end be select to receive a award if you have a match please call quote claim code standard rat app',
 'i be go to sao mu today will be do only at',
 'predict wat time ll finish buy',
 'good stuff will do',
 'just so that you know yetunde hasn t send money yet i just send her a text not to bother send so its over you dont have to involve yourself in anything i shouldn t have impose anything on you in the first place so for that i apologise',
 'be you there in room',
 'hey girl how r u hope u r well me an del r bak again long time no c give me a call sum time from lucyxx',
 'k k how much do it cost',
 'i m home',
 'dear will call tmorrow pls accomodate',
 'first answer my question',
 'sunshine quiz wkly q win a top sony dvd player if u know which country the algarve be in txt ansr to sp tyrone',
 'want get lay tonight want real dog locations send direct ur mob join the uk s largest dog network bt txting gravel to nt ec a p msg p',
 'i only haf msn it s yijue hotmail com',
 'he be there you call and meet him',
 'no no i will check all room befor activities',
 'you ll not rcv any more msgs from the chat svc for free hardcore service text go to if u get nothing u must age verify with yr network try again',
 'get c i lazy to type i forget in lect i saw a pouch but like not v nice',
 'k text me when you re on the way',
 'sir wait for your mail',
 'a swt think nver get tire of do little things lovable persons coz somtimes those little things occupy d biggest part in their hearts gud ni',
 'i know you be can you pls open the back',
 'yes see ya not on the dot',
 'whats the staff name who be take class for us',
 'freemsg why haven t you reply to my text i m randy sexy female and live local luv to hear from u netcollex ltd p per msg reply stop to end',
 'ummma will call after check in our life will begin from qatar so pls pray very hard',
 'k i delete my contact that why',
 'sindu get job in birla soft',
 'the wine be flow and i m i have nevering',
 'yup i thk cine be better cos no need go down plaza mah',
 'ok ur typical reply',
 'as per your request melle melle oru minnaminunginte nurungu vettam have be set as your callertune for all callers press to copy your friends callertune',
 'you be everywhere dirt on the floor the windows even on my shirt and sometimes when i open my mouth you be all that come flow out i dream of my world without you then half my chores be out too a time of joy for me lot of tv show i ll see but i guess like all things you just must exist like rain hail and mist and when my time here be do you and i become one',
 'aaooooright be you at work',
 'i m leave my house now',
 'hello my love what be you do do you get to that interview today be you you happy be you be a good boy do you think of me be you miss me',
 'customer service annoncement you have a new years delivery wait for you please call now to arrange delivery',
 'you be a winner u have be specially select receive cash or a holiday flight inc speak to a live operator claim',
 'keep yourself safe for me because i need you and i miss you already and i envy everyone that see s you in real life',
 'new car and house for my parent i have only new job in hand',
 'i m so in love with you i m excite each day i spend with you you make me so happy',
 'pls stop bootydelious f be invite you to be her friend reply yes or no see her www sms ac u bootydelious stop send stop frnd to',
 'bangbabes ur order be on the way u should receive a service msg download ur content if u do not goto wap bangb tv on ur mobile internet service menu',
 'i place all ur point on e culture module already',
 'urgent we be try to contact you last weekend draw show that you have win a prize guarantee call claim code s valid hrs only',
 'hi frnd which be best way to avoid missunderstding wit our beloved one s',
 'great escape i fancy the bridge but need her lager see you tomo',
 'yes it completely in out of form clark also utter waste',
 'sir i need axis bank account no and bank address',
 'hmmm thk sure get time to hop ard ya can go free abt muz call u to discuss liao',
 'what time you come down later',
 'bloody hell cant believe you forget my surname mr ill give u a clue its spanish and begin with m',
 'well i m gonna finish my bath now have a good fine night',
 'let me know when you ve get the money so carlos can make the call',
 'u still go to the mall',
 'turn out my friends be stay for the whole show and win t be back til lt gt so feel free to go ahead and smoke that lt gt worth',
 'text her if she doesnt reply let me know so i can have her log in',
 'hi you just speak to maneesha v we d like to know if you be satisfy with the experience reply toll free with yes or no',
 'you lift my hop with the offer of money i be in need especially when the end of the month approach and it hurt my study anyways have a gr weekend',
 'lol no u can trust me',
 'ok i be a gentleman and will treat you with dignity and respect',
 'he will you guy close',
 'go on nothing great bye',
 'hello handsome be you find that job not be lazy work towards get back that net for mummy where s my boytoy now do he miss me',
 'haha awesome be there in a minute',
 'please call our customer service representative on freephone between be pm as you have win a guarantee cash or prize',
 'have you get xmas radio time if not i will get it now',
 'i jus reach home i go bathe first but my sis use net tell u when she finish k',
 'be you unique enough find out from th august www areyouunique co uk',
 'i m sorry i ve join the league of people that dont keep in touch you mean a great deal to me you have be a friend at all time even at great personal cost do have a great week',
 'hi finally i complete the course',
 'it will stop on itself i however suggest she stay with someone that will be able to give ors for every stool',
 'how be you do hope you ve settle in for the new school year just wishin you a gr day',
 'gud mrng dear hav a nice day',
 'do u get that persons story',
 'be your hamster dead hey so tmr i meet you at pm orchard mrt',
 'hi its kate how be your even i hope i can see you tomorrow for a bite but i have to bloody babyjontet txt back if u can xxx',
 'find it enc lt gt where you at',
 'i send you lt gt buck',
 'hello darlin ive finish college now so txt me when u finish if u can love kate xxx',
 'your account have be refill successfully by inr lt decimal gt your keralacircle prepay account balance be rs lt decimal gt your transaction id be kr lt gt',
 'goodmorning sleep ga',
 'u call me alter at ok',
 'say until like dat i dun buy ericsson oso cannot oredi lar',
 'as i enter my cabin my pa say happy b day boss i felt special she askd me lunch after lunch she invite me to her apartment we go there',
 'aight yo dats straight dogg',
 'you please give us connection today itself before lt decimal gt or refund the bill',
 'both i shoot big load so get ready',
 'what s up bruv hope you have a great break do have a reward semester',
 'home so we can always chat',
 'k k good study well',
 'yup how noe leh',
 'sound great be you home now',
 'finally the match head towards draw as your prediction',
 'tire i haven t sleep well the past few nights',
 'easy ah sen get select mean its good',
 'i have to take exam with march',
 'yeah you should i think you can use your gt atm now to register not sure but if there s anyway i can help let me know but when you do be sure you be ready',
 'ok no prob take ur time',
 'there be os call ubandu which will run without instal in hard disk you can use that os to copy the important file in system and give it to repair shop',
 'sorry i ll call later',
 'u say leh of course nothing happen lar not say v romantic jus a bite only lor i thk e nite scenery not so nice leh',
 'new mobiles from must go txt nokia to no collect yours today from only www tc biz optout gbp mtmsg',
 'would really appreciate if you call me just need someone to talk to',
 'will u meet ur dream partner soon be ur career off a flyng start find out free txt horo follow by ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life be more strict than teacher bcoz teacher teach lesson amp then conduct exam but life first conduct exam amp then teach lessons happy morning',
 'dear good morning now only i be up',
 'get down in gandhipuram and walk to cross cut road right side lt gt street road and turn at first right',
 'dear we be go to our rubber place',
 'sorry battery die yeah i m here',
 'yes here tv be always available in work place',
 'text meet someone sexy today u can find a date or even flirt its up to u join just p reply with name age eg sam msg recd thirtyeight pence',
 'i have print it oh so lt gt come upstairs',
 'or ill be a little closer like at the bus stop on the same street',
 'where be you when wil you reach here',
 'new theory argument win d situation but lose the person so dont argue with ur friends just kick them amp say i m always correct',
 'u have a secret admirer who be look make contact with u find out who they r reveal who think ur so special call on',
 'tomarrow final hear on my laptop case so i cant',
 'pleassssssseeeeee tel me v avent do sportsx',
 'okay no no just shin on that be mean to be sign but that sound better',
 'although i tell u dat i m into baig face watch now but i really like e watch u give cos it s fr u thanx everything dat u ve do today i m touch',
 'u don t remember that old commercial',
 'too late i say i have the website i didn t i have or dont have the slippers',
 'i ask you to call him now ok',
 'kallis wont bat in nd innings',

In [41]:
len(corpus)

5572

In [42]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [43]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [44]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'get',
  'amore',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'live',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'be',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'be',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['as',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'have',
  'be',
  'set',
  'as',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  'press',
  'to',
  'copy',
  'your',
  'friends',
  'callertune'],
 ['winner',
  'as',
  'value',
  'network',
  'customer',
  'you',
  'have',
  'be',
  'select',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hours',
  'only'],
 ['have',
  'your',
  'mobile',
  'months',
  'or',
  'more',
  'entitle',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobiles',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  've',
  'cry',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'days',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'win',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'be',
  'search',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'promise',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'grant',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'be',
  'wonderful',
  'and',
  'bless',
  'at',
  'all',
  'time'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watch', 'here'],
 ['eh',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'do',
  'he',
  'naughty',
  'make',
  'until',
  'wet'],
 ['fine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'its',
  'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goals',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wales',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['be', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['go', 'to', 'try', 'for', 'months', 'ha', 'ha', 'only', 'joke'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'be', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'force',
  'myself',
  'to',
  'eat',
  'slice',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'be',
  'get',
  'worry',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convince'],
 ['do',
  'you',
  'catch',
  'the',
  'bus',
  'be',
  'you',
  'fry',
  'an',
  'egg',
  'do',
  'you',
  'make',
  'tea',
  'be',
  'you',
  'eat',
  'your',
  'mom',
  'leave',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'pack',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['ahhh',
  'work',
  'vaguely',
  'remember',
  'that',
  'what',
  'do',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'be',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'be',
  'sarcastic',
  'or',
  'that',
  'that',
  'why',
  'doesn',
  'want',
  'to',
  'live',
  'with',
  'us'],
 ['yeah',
  'he',
  'get',
  'in',
  'at',
  'and',
  'be',
  'apologetic',
  'have',
  'fall',
  'out',
  'and',
  'she',
  'be',
  'actin',
  'like',
  'spoil',
  'child',
  'and',
  'he',
  'get',
  'catch',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'win',
  'go',
  'there',
  'not',
  'do',
  'too',
  'badly',
  'cheer',
  'you'],
 ['tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'faint',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'do',
  'quick',
  'have',
  'cuppa'],
 ['thank',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charge',
  'month',
  'please',
  'confirm',
  'by',
  'reply',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charge'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timings',
  'then',
  'msg',
  'again',
  'xuhui',
  'go',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'be',
  'at',
  'be'],
 ['oops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'do'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'how',
  'you',
  'and',
  'how',
  'do',
  'saturday',
  'go',
  'be',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'decide',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'try',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watts',
  'just',
  'want',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['do',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'try',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sms',
  'for',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'be', 'you', 'see'],
 ['great',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endow',
  'be',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'miss', 'call'],
 ['didn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'go', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'maybe',
  'ask',
  'around',
  'bite'],
 ['don',
  'know',
  'how',
  'stubborn',
  'be',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'keep',
  'tell',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospitals',
  'be',
  'for',
  'weak',
  'suckers'],
 ['what',
  'you',
  'think',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'be',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'have',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  'crash',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realize',
  'that',
  'you',
  'be',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'think',
  'you',
  'like',
  'it',
  'since',
  'be',
  'do',
  'the',
  'best',
  'could',
  'and',
  'you',
  'always',
  'seem',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'sorry',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorry',
  'offer',
  'sorry',
  'your',
  'room',
  'be',
  'so',
  'embarassing'],
 ['sms',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'do',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pass',
  'for',
  'be',
  'yours',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'll', 'call', 'later', 'in', 'meet'],
 ['tell', 'where', 'you', 'reach'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'be',
  'kill',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girls', 'be', 'situation', 'seekers'],
 ['its', 'part', 'of', 'check', 'iq'],
 ['sorry',
  'my',
  'roommates',
  'take',
  'forever',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'say',
  'wun',
  'cut',
  'short',
  'he',
  'say',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['as',
  'value',
  'customer',
  'be',
  'please',
  'to',
  'advise',
  'you',
  'that',
  'follow',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'be',
  'award',
  'with',
  'bonus',
  'prize',
  'call'],
 ['today',
  'be',
  'song',
  'dedicate',
  'day',
  'which',
  'song',
  'will',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'award',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'ls',
  'aj'],
 ['do',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finish', 'class', 'where', 'be', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['where', 'be', 'you', 'how', 'do', 'you', 'perform'],
 ['can', 'call', 'me', 'now'],
 ['be', 'wait', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'be',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['like', 'you', 'people', 'very', 'much', 'but', 'be', 'very', 'shy', 'pa'],
 ['do', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['its',
  'not',
  'the',
  'same',
  'here',
  'still',
  'look',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['sorry', 'll', 'call', 'later'],
 ['do', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'be', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['call',
  'you',
  'later',
  'don',
  'have',
  'network',
  'if',
  'urgnt',
  'sms',
  'me'],
 ['for',
  'real',
  'when',
  'get',
  'on',
  'yo',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'do',
  'already',
  'use',
  'all',
  'my',
  'multis'],
 ['yes',
  'start',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'come',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'pain',
  'be',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'spend',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'haven',
  'do',
  'any',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'include',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pour',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'smile'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'be',
  'pm',
  'as',
  'you',
  'have',
  'win',
  'guarantee',
  'cash',
  'or',
  'prize'],
 ['havent',
  'plan',
  'to',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'only',
  'get',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'be',
  'wait',
  'to',
  'be',
  'collect',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watch', 'telugu', 'movie', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'be',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'bite',
  'of',
  'run',
  'forget',
  'that',
  'have',
  'hairdressers',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'do',
  'that',
  'cause',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  'text',
  'me',
  'anymore',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'as',
  'long',
  'as',
  'its',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'ams',
  'xx'],
 ['still',
  'look',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'go',
  'the',
  'drive',
  'test',
  'yet'],
 ['as',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'have',
  'be',
  'set',
  'as',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  'press',
  'to',
  'copy',
  'your',
  'friends',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'once',
  'give',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'change',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'change',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thank',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thank',
  'you',
  'for',
  'make',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'consider',
  'my',
  'computer',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'be',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lie',
  'then',
  'again',
  'be',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'he', 'busy'],
 ['what', 'be', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['go', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'cos',
  'like',
  'try',
  'new',
  'things',
  'but',
  'scar',
  'dun',
  'like',
  'mah',
  'cos',
  'say',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'be',
  'try',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'win',
  'prize',
  'guarantee',
  'call',
  'claim',
  'code',
  'valid',
  'hrs',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happen'],
 ['as',
  'enter',
  'my',
  'cabin',
  'my',
  'pa',
  'say',
  'happy',
  'day',
  'boss',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invite',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'go',
  'there'],
 ['you',
  'be',
  'winner',
  'have',
  'be',
  'specially',
  'select',
  'receive',
  'or',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'need'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'inform',
  'me',
  'that',
  'he',
  'pay',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expire'],
 ['urgent',
  'your',
  'mobile',
  'no',
  'be',
  'award',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'be',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['here',
  'be',
  'my',
  'new',
  'address',
  'apples',
  'pair',
  'all',
  'that',
  'malarky'],
 ['todays',
  'voda',
  'number',
  'end',
  'be',
  'select',
  'to',
  'receive',
  'award',
  'if',
  'you',
  'have',
  'match',
  'please',
  'call',
  'quote',
  'claim',
  'code',
  'standard',
  'rat',
  'app'],
 ['be', 'go', 'to', 'sao', 'mu', 'today', 'will', 'be', 'do', 'only', 'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buy'],
 ['good', 'stuff', 'will', 'do'],
 ['just',
  'so',
  'that',
  'you',
  'know',
  'yetunde',
  'hasn',
  'send',
  'money',
  'yet',
  'just',
  'send',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'send',
  'so',
  'its',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involve',
  'yourself',
  'in',
  'anything',
  'shouldn',
  'have',
  'impose',
  'anything',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologise'],
 ['be', 'you', 'there', 'in', 'room'],
 ['hey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'do', 'it', 'cost'],
 ['home'],
 ['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'my', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'country',
  'the',
  'algarve',
  'be',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'lay',
  'tonight',
  'want',
  'real',
  'dog',
  'locations',
  'send',
  'direct',
  'ur',
  'mob',
  'join',
  'the',
  'uk',
  'largest',
  'dog',
  'network',
  'bt',
  'txting',
  'gravel',
  'to',
  'nt',
  'ec',
  'msg'],

In [45]:
len(words)

5569

In [46]:
import gensim

In [47]:
model=gensim.models.Word2Vec(words)

In [48]:
model.wv.index_to_key

['be',
 'to',
 'you',
 'the',
 'and',
 'in',
 'have',
 'me',
 'my',
 'it',
 'do',
 'for',
 'get',
 'call',
 'your',
 'of',
 'that',
 'go',
 'on',
 'now',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'at',
 'will',
 'ur',
 'if',
 'with',
 'no',
 'just',
 'this',
 'come',
 'gt',
 'lt',
 'how',
 'up',
 'when',
 'ok',
 'what',
 'know',
 'free',
 'from',
 'send',
 'all',
 'out',
 'll',
 'like',
 'time',
 'love',
 'want',
 'good',
 'day',
 'then',
 'there',
 'he',
 'say',
 'its',
 'only',
 'think',
 'tell',
 'take',
 'text',
 'need',
 'win',
 'see',
 'txt',
 'as',
 'make',
 'one',
 'by',
 'stop',
 'don',
 'she',
 'home',
 'about',
 'reply',
 'lor',
 'sorry',
 'today',
 'still',
 'back',
 'da',
 'dont',
 'our',
 'mobile',
 'phone',
 'please',
 'hi',
 'meet',
 'new',
 'work',
 'they',
 'later',
 'miss',
 'any',
 'pls',
 'her',
 'ask',
 'give',
 'some',
 'week',
 'dear',
 'message',
 'here',
 'who',
 'wait',
 'well',
 'where',
 'leave',
 'night',
 're',
 'try',
 'much',
 'hope',
 'an',
 'oh',
 'claim',
 'great',
 'msg',
 'hey',
 'him',
 'number',
 'more',
 'too',
 'happy',
 'thank',
 'wat',
 'way',
 'yes',
 'find',
 'www',
 've',
 'should',
 'let',
 'prize',
 'feel',
 'right',
 'tomorrow',
 'even',
 'pick',
 'already',
 'tone',
 'after',
 'cash',
 'amp',
 'sleep',
 'im',
 'yeah',
 'really',
 'keep',
 'why',
 'life',
 'them',
 'buy',
 'care',
 'very',
 'last',
 'babe',
 'morning',
 'service',
 'cos',
 'would',
 'anything',
 'com',
 'contact',
 'start',
 'uk',
 'also',
 'nokia',
 'lol',
 'use',
 'every',
 'wish',
 'look',
 'smile',
 'sure',
 'min',
 'end',
 'urgent',
 'over',
 'show',
 'something',
 'watch',
 'award',
 'gud',
 'mean',
 'again',
 'us',
 'finish',
 'before',
 'cant',
 'place',
 'box',
 'first',
 'his',
 'help',
 'thing',
 'guy',
 'someone',
 'chat',
 'nice',
 'next',
 'off',
 'which',
 'talk',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'tonight',
 'many',
 'mins',
 'late',
 'name',
 'per',
 'ya',
 'plan',
 'sms',
 'always',
 'gonna',
 'customer',
 'wan',
 'down',
 'live',
 'lot',
 'check',
 'co',
 'other',
 'shop',
 'pm',
 'friends',
 'dun',
 'things',
 'forget',
 'eat',
 'st',
 'special',
 'hello',
 'friend',
 'fine',
 'may',
 'haha',
 'guarantee',
 'people',
 'best',
 'thk',
 'happen',
 'yet',
 'same',
 'reach',
 'year',
 'offer',
 'heart',
 'ppm',
 'bite',
 'pay',
 'days',
 'stuff',
 'sit',
 'play',
 'didn',
 'cost',
 'fuck',
 'god',
 'line',
 'th',
 'holiday',
 'class',
 'person',
 'hear',
 'man',
 'lunch',
 'receive',
 'enjoy',
 'few',
 'draw',
 'job',
 'speak',
 'cs',
 'house',
 'drive',
 'never',
 'worry',
 'mind',
 'bring',
 'wake',
 'ill',
 'account',
 'better',
 'cool',
 'thats',
 'yup',
 'ready',
 'guess',
 'long',
 'date',
 'pobox',
 'game',
 'lose',
 'dat',
 'weekend',
 'car',
 'chance',
 'wk',
 'real',
 'half',
 'book',
 'than',
 'because',
 'sir',
 'bt',
 'yo',
 'month',
 'room',
 'latest',
 'problem',
 'luv',
 'nothing',
 'po',
 'wanna',
 'run',
 'camera',
 'lar',
 'world',
 'shit',
 'big',
 'liao',
 'join',
 'another',
 'charge',
 'question',
 'put',
 'kiss',
 'into',
 'stay',
 'age',
 'girl',
 'birthday',
 'ah',
 'sweet',
 'dinner',
 'xxx',
 'quite',
 'land',
 'ever',
 'might',
 'jus',
 'hrs',
 'remember',
 'network',
 'video',
 'landline',
 'collect',
 'wont',
 'apply',
 'probably',
 'two',
 'baby',
 'thanx',
 'tv',
 'dream',
 'aight',
 'change',
 'hurt',
 'bed',
 'pa',
 'once',
 'nd',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'minutes',
 'shall',
 'nite',
 'boy',
 'answer',
 'part',
 'maybe',
 'ringtone',
 'bus',
 'fun',
 'rate',
 'office',
 'orange',
 'dunno',
 'gift',
 'walk',
 'easy',
 'between',
 'code',
 'select',
 'hour',
 'true',
 'didnt',
 'everything',
 'face',
 'sound',
 'leh',
 'little',
 'mail',
 'anyway',
 'xx',
 'dis',
 'town',
 'dad',
 'wife',
 'bore',
 'detail',
 'drink',
 'those',
 'school',
 'pound',
 'enough',
 'await',
 'while',
 'texts',
 'post',
 'read',
 'tmr',
 'years',
 'without',
 'afternoon',
 'pain',
 'most',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'must',
 'test',
 'price',
 'okay',
 'since',
 'decide',
 'credit',
 'valid',
 'though',
 'wif',
 'until',
 'collection',
 'wot',
 'break',
 'able',
 'smoke',
 'til',
 'abt',
 'close',
 'mob',
 'plus',
 'away',
 'de',
 'plz',
 'ring',
 'decimal',
 'order',
 'enter',
 'juz',
 'haven',
 'wen',
 'colour',
 'drop',
 'wonder',
 'attempt',
 'weekly',
 'hold',
 'music',
 'hand',
 'top',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'update',
 'lei',
 'goin',
 'online',
 'these',
 'dude',
 'optout',
 'head',
 'oso',
 'id',
 'coz',
 'haf',
 'food',
 'trip',
 'yours',
 'net',
 'family',
 'sch',
 'either',
 'tot',
 'friendship',
 'club',
 'hot',
 'gr',
 'address',
 'spend',
 'yourself',
 'delivery',
 'invite',
 'ard',
 'national',
 'search',
 'hours',
 'set',
 'sad',
 'together',
 'listen',
 'sae',
 'beautiful',
 'full',
 'choose',
 'wid',
 'vouchers',
 'both',
 'touch',
 'believe',
 'nt',
 'todays',
 'busy',
 'cause',
 'movie',
 'bonus',
 'second',
 'http',
 'understand',
 'email',
 'train',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'die',
 'noe',
 'story',
 'study',
 'hop',
 'open',
 'match',
 'old',
 'info',
 'brother',
 'pic',
 'rite',
 'sell',
 'mum',
 'pics',
 'simple',
 'suite',
 'mths',
 'okie',
 'park',
 'wil',
 'minute',
 'awesome',
 'content',
 'parent',
 'dog',
 'expire',
 'private',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'treat',
 'auction',
 'anyone',
 'laugh',
 'pub',
 'neva',
 'mine',
 'opt',
 'gd',
 'reason',
 'card',
 'sort',
 'unsubscribe',
 'angry',
 'reveal',
 'company',
 'fancy',
 'everyone',
 'msgs',
 'download',
 'move',
 'tho',
 'value',
 'final',
 'available',
 'alone',
 'knw',
 'sun',
 'voucher',
 'whatever',
 'visit',
 'forward',
 'sister',
 'sis',
 'worth',
 'carlos',
 'bank',
 'each',
 'whats',
 'type',
 'statement',
 'ticket',
 'lucky',
 'pass',
 'seem',
 'lesson',
 'joke',
 'hows',
 'surprise',
 'party',
 'mat',
 'add',
 'fast',
 'sub',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'return',
 'light',
 'far',
 'anytime',
 'gbp',
 'bill',
 'rs',
 'college',
 'boytoy',
 'log',
 'frnd',
 'hard',
 'ltd',
 'ni',
 'yr',
 'quiz',
 'identifier',
 'hit',
 'prob',
 'girls',
 'saturday',
 'mom',
 'catch',
 'smth',
 'ha',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'drug',
 'weeks',
 'clean',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'project',
 'interest',
 'congratulations',
 'tel',
 'case',
 'secret',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'bath',
 'wit',
 'player',
 'friday',
 'operator',
 'rain',
 'save',
 'follow',
 'cut',
 'camcorder',
 'confirm',
 'crazy',
 'wasn',
 'support',
 'earlier',
 'mate',
 'snow',
 'kid',
 'savamob',
 'frm',
 'cum',
 'scream',
 'suppose',
 'ten',
 'rock',
 'jay',
 'fone',
 'blue',
 'own',
 'unlimited',
 'fix',
 'fr',
 'tc',
 'course',
 'their',
 'tire',
 'mu',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'luck',
 'film',
 'na',
 'gn',
 'murder',
 'yrs',
 'store',
 'eye',
 'mayb',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'marry',
 'un',
 'within',
 'fight',
 'remove',
 'sk',
 'india',
 'ass',
 'couple',
 'motorola',
 'currently',
 'ago',
 'figure',
 'txts',
 'christmas',
 'bslvyl',
 'stupid',
 'single',
 'dnt',
 'side',
 'teach',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'pray',
 'caller',
 'felt',
 'mah',
 'shower',
 'load',
 'hee',
 'etc',
 'almost',
 'turn',
 'eh',
 'promise',
 'mobiles',
 'months',
 'reward',
 'press',
 'difficult',
 'write',
 'gal',
 'grin',
 'information',
 'fill',
 'extra',
 'ugh',
 'ans',
 'xy',
 'darren',
 'gym',
 'through',
 'max',
 'redeem',
 'ipod',
 'rent',
 'doin',
 'rental',
 'slow',
 'ish',
 'via',
 'ge',
 'swing',
 'laptop',
 'bcoz',
 'semester',
 'complete',
 'deal',
 'direct',
 'uncle',
 'askd',
 'computer',
 'stand',
 'gotta',
 'complimentary',
 'song',
 'correct',
 'red',
 'ac',
 'wow',
 'crave',
 'cheer',
 'fall',
 'comp',
 'police',
 'slowly',
 'fantasy',
 'nobody',
 'cancel',
 'convey',
 'truth',
 'asap',
 'whenever',
 'ts',
 'noon',
 'warm',
 'blood',
 'monday',
 'yep',
 'share',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'din',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'wana',
 'disturb',
 'expect',
 'register',
 'exam',
 'kate',
 'orchard',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'rat',
 'page',
 'loan',
 'include',
 'rply',
 'abiola',
 'comin',
 'eg',
 'link',
 'wap',
 'copy',
 'request',
 'usf',
 'std',
 'empty',
 'cook',
 'excuse',
 'hw',
 'fact',
 'cover',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'regard',
 'rd',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'wed',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'glad',
 'fantastic',
 'gap',
 'king',
 'em',
 'cheap',
 'across',
 'less',
 'near',
 'water',
 'style',
 'different',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'moment',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'sign',
 'bathe',
 'trust',
 'waste',
 'sony',
 'del',
 'quote',
 'inform',
 'representative',
 'il',
 'short',
 'forever',
 'hospital',
 'oops',
 'myself',
 'england',
 'callertune',
 'nah',
 'cup',
 'la',
 'tear',
 'sofa',
 'colleagues',
 'flag',
 'thinkin',
 'list',
 'excellent',
 'moral',
 'tht',
 'others',
 'mode',
 'mon',
 'deliver',
 'digital',
 'hiya',
 'against',
 'wear',
 'mo',
 'iam',
 'user',
 'tampa',
 'charity',
 'comuk',
 'ones',
 'bid',
 'norm',
 'possible',
 'bold',
 'ho',
 'pc',
 'valentine',
 'hurry',
 'remind',
 'self',
 'fat',
 'children',
 'silent',
 ...]

In [25]:
model.wv.key_to_index

{'get': 0,
 'call': 1,
 'go': 2,
 'ur': 3,
 'come': 4,
 'gt': 5,
 'lt': 6,
 'ok': 7,
 'know': 8,
 'free': 9,
 'send': 10,
 'like': 11,
 'time': 12,
 'love': 13,
 'want': 14,
 'good': 15,
 'day': 16,
 'say': 17,
 'think': 18,
 'tell': 19,
 'take': 20,
 'text': 21,
 'need': 22,
 'see': 23,
 'txt': 24,
 'make': 25,
 'one': 26,
 'stop': 27,
 'home': 28,
 'reply': 29,
 'lor': 30,
 'sorry': 31,
 'today': 32,
 'still': 33,
 'back': 34,
 'da': 35,
 'dont': 36,
 'mobile': 37,
 'phone': 38,
 'please': 39,
 'hi': 40,
 'meet': 41,
 'new': 42,
 'work': 43,
 'later': 44,
 'miss': 45,
 'pls': 46,
 'ask': 47,
 'give': 48,
 'week': 49,
 'dear': 50,
 'message': 51,
 'wait': 52,
 'well': 53,
 'leave': 54,
 'night': 55,
 'try': 56,
 'much': 57,
 'hope': 58,
 'oh': 59,
 'claim': 60,
 'great': 61,
 'msg': 62,
 'hey': 63,
 'number': 64,
 'happy': 65,
 'thank': 66,
 'wat': 67,
 'way': 68,
 'yes': 69,
 'find': 70,
 'www': 71,
 'let': 72,
 'prize': 73,
 'feel': 74,
 'right': 75,
 'win': 76,
 'tomorrow': 77,
 'even': 78,
 'pick': 79,
 'already': 80,
 'tone': 81,
 'cash': 82,
 'amp': 83,
 'sleep': 84,
 'im': 85,
 'yeah': 86,
 'really': 87,
 'keep': 88,
 'life': 89,
 'buy': 90,
 'care': 91,
 'last': 92,
 'babe': 93,
 'morning': 94,
 'service': 95,
 'cos': 96,
 'would': 97,
 'anything': 98,
 'com': 99,
 'contact': 100,
 'start': 101,
 'uk': 102,
 'also': 103,
 'nokia': 104,
 'lol': 105,
 'use': 106,
 'every': 107,
 'wish': 108,
 'look': 109,
 'smile': 110,
 'sure': 111,
 'min': 112,
 'end': 113,
 'urgent': 114,
 'show': 115,
 'something': 116,
 'watch': 117,
 'award': 118,
 'gud': 119,
 'mean': 120,
 'us': 121,
 'finish': 122,
 'cant': 123,
 'place': 124,
 'box': 125,
 'first': 126,
 'help': 127,
 'thing': 128,
 'guy': 129,
 'someone': 130,
 'chat': 131,
 'nice': 132,
 'next': 133,
 'talk': 134,
 'soon': 135,
 'word': 136,
 'around': 137,
 'money': 138,
 'could': 139,
 'tonight': 140,
 'many': 141,
 'mins': 142,
 'late': 143,
 'name': 144,
 'per': 145,
 'ya': 146,
 'plan': 147,
 'sms': 148,
 'always': 149,
 'gonna': 150,
 'customer': 151,
 'wan': 152,
 'live': 153,
 'lot': 154,
 'check': 155,
 'co': 156,
 'shop': 157,
 'pm': 158,
 'friends': 159,
 'dun': 160,
 'things': 161,
 'forget': 162,
 'eat': 163,
 'st': 164,
 'special': 165,
 'hello': 166,
 'friend': 167,
 'fine': 168,
 'may': 169,
 'haha': 170,
 'guarantee': 171,
 'people': 172,
 'best': 173,
 'thk': 174,
 'happen': 175,
 'yet': 176,
 'reach': 177,
 'year': 178,
 'offer': 179,
 'do': 180,
 'heart': 181,
 'ppm': 182,
 'bite': 183,
 'pay': 184,
 'days': 185,
 'stuff': 186,
 'sit': 187,
 'play': 188,
 'cost': 189,
 'fuck': 190,
 'god': 191,
 'line': 192,
 'th': 193,
 'holiday': 194,
 'class': 195,
 'person': 196,
 'hear': 197,
 'man': 198,
 'lunch': 199,
 'receive': 200,
 'enjoy': 201,
 'draw': 202,
 'job': 203,
 'speak': 204,
 'cs': 205,
 'house': 206,
 'drive': 207,
 'never': 208,
 'worry': 209,
 'mind': 210,
 'bring': 211,
 'wake': 212,
 'ill': 213,
 'account': 214,
 'better': 215,
 'cool': 216,
 'thats': 217,
 'yup': 218,
 'ready': 219,
 'guess': 220,
 'long': 221,
 'date': 222,
 'pobox': 223,
 'game': 224,
 'lose': 225,
 'dat': 226,
 'weekend': 227,
 'car': 228,
 'chance': 229,
 'wk': 230,
 'real': 231,
 'half': 232,
 'book': 233,
 'sir': 234,
 'bt': 235,
 'yo': 236,
 'month': 237,
 'room': 238,
 'latest': 239,
 'problem': 240,
 'luv': 241,
 'nothing': 242,
 'po': 243,
 'wanna': 244,
 'run': 245,
 'camera': 246,
 'lar': 247,
 'world': 248,
 'shit': 249,
 'big': 250,
 'liao': 251,
 'join': 252,
 'another': 253,
 'charge': 254,
 'question': 255,
 'put': 256,
 'kiss': 257,
 'stay': 258,
 'age': 259,
 'girl': 260,
 'birthday': 261,
 'ah': 262,
 'sweet': 263,
 'dinner': 264,
 'xxx': 265,
 'quite': 266,
 'land': 267,
 'ever': 268,
 'might': 269,
 'jus': 270,
 'hrs': 271,
 'remember': 272,
 'network': 273,
 'video': 274,
 'landline': 275,
 'collect': 276,
 'wont': 277,
 'apply': 278,
 'probably': 279,
 'two': 280,
 'baby': 281,
 'thanx': 282,
 'tv': 283,
 'dream': 284,
 'aight': 285,
 'change': 286,
 'hurt': 287,
 'bed': 288,
 'pa': 289,
 'nd': 290,
 'early': 291,
 'point': 292,
 'princess': 293,
 'bad': 294,
 'den': 295,
 'actually': 296,
 'minutes': 297,
 'shall': 298,
 'nite': 299,
 'boy': 300,
 'answer': 301,
 'part': 302,
 'maybe': 303,
 'ringtone': 304,
 'bus': 305,
 'fun': 306,
 'rate': 307,
 'office': 308,
 'orange': 309,
 'dunno': 310,
 'gift': 311,
 'walk': 312,
 'easy': 313,
 'code': 314,
 'select': 315,
 'hour': 316,
 'true': 317,
 'didnt': 318,
 'everything': 319,
 'face': 320,
 'sound': 321,
 'leh': 322,
 'little': 323,
 'mail': 324,
 'anyway': 325,
 'xx': 326,
 'dis': 327,
 'town': 328,
 'dad': 329,
 'wife': 330,
 'bore': 331,
 'detail': 332,
 'drink': 333,
 'school': 334,
 'pound': 335,
 'enough': 336,
 'await': 337,
 'texts': 338,
 'post': 339,
 'read': 340,
 'tmr': 341,
 'years': 342,
 'without': 343,
 'afternoon': 344,
 'pain': 345,
 'entry': 346,
 'important': 347,
 'hav': 348,
 'xmas': 349,
 'sexy': 350,
 'must': 351,
 'test': 352,
 'price': 353,
 'okay': 354,
 'since': 355,
 'decide': 356,
 'credit': 357,
 'valid': 358,
 'though': 359,
 'wif': 360,
 'collection': 361,
 'wot': 362,
 'break': 363,
 'able': 364,
 'smoke': 365,
 'til': 366,
 'abt': 367,
 'close': 368,
 'mob': 369,
 'plus': 370,
 'away': 371,
 'de': 372,
 'plz': 373,
 'ring': 374,
 'decimal': 375,
 'order': 376,
 'enter': 377,
 'juz': 378,
 'wen': 379,
 'colour': 380,
 'drop': 381,
 'wonder': 382,
 'attempt': 383,
 'weekly': 384,
 'hold': 385,
 'music': 386,
 'hand': 387,
 'top': 388,
 'else': 389,
 'havent': 390,
 'hair': 391,
 'double': 392,
 'yesterday': 393,
 'saw': 394,
 'till': 395,
 'alright': 396,
 'update': 397,
 'lei': 398,
 'goin': 399,
 'online': 400,
 'dude': 401,
 'optout': 402,
 'head': 403,
 'oso': 404,
 'id': 405,
 'coz': 406,
 'haf': 407,
 'food': 408,
 'trip': 409,
 'net': 410,
 'family': 411,
 'sch': 412,
 'either': 413,
 'tot': 414,
 'friendship': 415,
 'club': 416,
 'hot': 417,
 'gr': 418,
 'address': 419,
 'spend': 420,
 'delivery': 421,
 'invite': 422,
 'ard': 423,
 'national': 424,
 'search': 425,
 'hours': 426,
 'set': 427,
 'sad': 428,
 'together': 429,
 'listen': 430,
 'sae': 431,
 'beautiful': 432,
 'full': 433,
 'choose': 434,
 'wid': 435,
 'vouchers': 436,
 'touch': 437,
 'believe': 438,
 'nt': 439,
 'todays': 440,
 'busy': 441,
 'cause': 442,
 'movie': 443,
 'bonus': 444,
 'second': 445,
 'http': 446,
 'understand': 447,
 'email': 448,
 'train': 449,
 'eve': 450,
 'poly': 451,
 'huh': 452,
 'chikku': 453,
 'row': 454,
 'die': 455,
 'noe': 456,
 'story': 457,
 'study': 458,
 'hop': 459,
 'open': 460,
 'match': 461,
 'old': 462,
 'info': 463,
 'brother': 464,
 'pic': 465,
 'rite': 466,
 'sell': 467,
 'mum': 468,
 'pics': 469,
 'simple': 470,
 'suite': 471,
 'mths': 472,
 'okie': 473,
 'park': 474,
 'wil': 475,
 'minute': 476,
 'awesome': 477,
 'content': 478,
 'parent': 479,
 'dog': 480,
 'expire': 481,
 'private': 482,
 'congrats': 483,
 'tomo': 484,
 'aft': 485,
 'news': 486,
 'hl': 487,
 'treat': 488,
 'auction': 489,
 'anyone': 490,
 'laugh': 491,
 'pub': 492,
 'neva': 493,
 'mine': 494,
 'opt': 495,
 'gd': 496,
 'reason': 497,
 'card': 498,
 'sort': 499,
 'unsubscribe': 500,
 'angry': 501,
 'reveal': 502,
 'company': 503,
 'fancy': 504,
 'everyone': 505,
 'msgs': 506,
 'download': 507,
 'move': 508,
 'tho': 509,
 'value': 510,
 'final': 511,
 'available': 512,
 'alone': 513,
 'knw': 514,
 'sun': 515,
 'voucher': 516,
 'whatever': 517,
 'visit': 518,
 'forward': 519,
 'sister': 520,
 'sis': 521,
 'worth': 522,
 'carlos': 523,
 'bank': 524,
 'whats': 525,
 'type': 526,
 'statement': 527,
 'ticket': 528,
 'lucky': 529,
 'pass': 530,
 'seem': 531,
 'lesson': 532,
 'joke': 533,
 'hows': 534,
 'surprise': 535,
 'party': 536,
 'mat': 537,
 'add': 538,
 'fast': 539,
 'sub': 540,
 'nyt': 541,
 'kind': 542,
 'welcome': 543,
 'bout': 544,
 'mobileupd': 545,
 'return': 546,
 'light': 547,
 'far': 548,
 'anytime': 549,
 'gbp': 550,
 'bill': 551,
 'rs': 552,
 'college': 553,
 'boytoy': 554,
 'log': 555,
 'frnd': 556,
 'hard': 557,
 'ltd': 558,
 'ni': 559,
 'yr': 560,
 'quiz': 561,
 'identifier': 562,
 'hit': 563,
 'prob': 564,
 'girls': 565,
 'saturday': 566,
 'mom': 567,
 'catch': 568,
 'smth': 569,
 'ha': 570,
 'wonderful': 571,
 'winner': 572,
 'chennai': 573,
 'least': 574,
 'wrong': 575,
 'lovely': 576,
 'drug': 577,
 'weeks': 578,
 'clean': 579,
 'sea': 580,
 'pretty': 581,
 'fri': 582,
 'outside': 583,
 'nope': 584,
 'term': 585,
 'project': 586,
 'interest': 587,
 'congratulations': 588,
 'tel': 589,
 'case': 590,
 'secret': 591,
 'oredi': 592,
 'goodmorning': 593,
 'darlin': 594,
 'mrng': 595,
 'finally': 596,
 'bath': 597,
 'wit': 598,
 'player': 599,
 'friday': 600,
 'operator': 601,
 'rain': 602,
 'save': 603,
 'follow': 604,
 'cut': 605,
 'camcorder': 606,
 'confirm': 607,
 'crazy': 608,
 'support': 609,
 'earlier': 610,
 'mate': 611,
 'snow': 612,
 'kid': 613,
 'savamob': 614,
 'frm': 615,
 'cum': 616,
 'scream': 617,
 'suppose': 618,
 'ten': 619,
 'rock': 620,
 'jay': 621,
 'fone': 622,
 'blue': 623,
 'unlimited': 624,
 'fix': 625,
 'fr': 626,
 'tc': 627,
 'course': 628,
 'tire': 629,
 'mu': 630,
 'hmm': 631,
 'frnds': 632,
 'whole': 633,
 'hungry': 634,
 'wq': 635,
 'sunday': 636,
 'freemsg': 637,
 'wkly': 638,
 'father': 639,
 'gas': 640,
 'john': 641,
 'luck': 642,
 'film': 643,
 'na': 644,
 'gn': 645,
 'murder': 646,
 'yrs': 647,
 'store': 648,
 'eye': 649,
 'mayb': 650,
 'sex': 651,
 'paper': 652,
 'area': 653,
 'happiness': 654,
 'yar': 655,
 'marry': 656,
 'un': 657,
 'within': 658,
 'fight': 659,
 'remove': 660,
 'sk': 661,
 'india': 662,
 'ass': 663,
 'couple': 664,
 'motorola': 665,
 'currently': 666,
 'ago': 667,
 'figure': 668,
 'txts': 669,
 'christmas': 670,
 'bslvyl': 671,
 'stupid': 672,
 'single': 673,
 'dnt': 674,
 'side': 675,
 'teach': 676,
 'march': 677,
 'balance': 678,
 'mr': 679,
 'hmmm': 680,
 'joy': 681,
 'pray': 682,
 'caller': 683,
 'felt': 684,
 'mah': 685,
 'shower': 686,
 'load': 687,
 'hee': 688,
 'etc': 689,
 'almost': 690,
 'turn': 691,
 'eh': 692,
 'promise': 693,
 'mobiles': 694,
 'months': 695,
 'reward': 696,
 'press': 697,
 'difficult': 698,
 'write': 699,
 'gal': 700,
 'grin': 701,
 'information': 702,
 'fill': 703,
 'extra': 704,
 'ugh': 705,
 'ans': 706,
 'xy': 707,
 'darren': 708,
 'gym': 709,
 'max': 710,
 'redeem': 711,
 'ipod': 712,
 'rent': 713,
 'doin': 714,
 'rental': 715,
 'slow': 716,
 'ish': 717,
 'via': 718,
 'ge': 719,
 'swing': 720,
 'laptop': 721,
 'bcoz': 722,
 'semester': 723,
 'complete': 724,
 'deal': 725,
 'direct': 726,
 'uncle': 727,
 'askd': 728,
 'computer': 729,
 'stand': 730,
 'gotta': 731,
 'complimentary': 732,
 'song': 733,
 'correct': 734,
 'red': 735,
 'ac': 736,
 'wow': 737,
 'crave': 738,
 'cheer': 739,
 'fall': 740,
 'comp': 741,
 'police': 742,
 'slowly': 743,
 'fantasy': 744,
 'nobody': 745,
 'cancel': 746,
 'convey': 747,
 'truth': 748,
 'asap': 749,
 'whenever': 750,
 'ts': 751,
 'noon': 752,
 'warm': 753,
 'blood': 754,
 'monday': 755,
 'yep': 756,
 'share': 757,
 'discount': 758,
 'hg': 759,
 'ex': 760,
 'weed': 761,
 'small': 762,
 'din': 763,
 'pete': 764,
 'rest': 765,
 'somebody': 766,
 'hmv': 767,
 'wana': 768,
 'disturb': 769,
 'expect': 770,
 'register': 771,
 'exam': 772,
 'kate': 773,
 'orchard': 774,
 'muz': 775,
 'safe': 776,
 'wine': 777,
 'lovable': 778,
 'txting': 779,
 'rat': 780,
 'page': 781,
 'loan': 782,
 'include': 783,
 'rply': 784,
 'abiola': 785,
 'comin': 786,
 'eg': 787,
 'link': 788,
 'wap': 789,
 'copy': 790,
 'request': 791,
 'usf': 792,
 'std': 793,
 'empty': 794,
 'cook': 795,
 'excuse': 796,
 'hw': 797,
 'fact': 798,
 'cover': 799,
 'bb': 800,
 'ringtones': 801,
 'energy': 802,
 'doctor': 803,
 'regard': 804,
 'rd': 805,
 'cr': 806,
 'ntt': 807,
 'otherwise': 808,
 'poor': 809,
 'wed': 810,
 'gettin': 811,
 'bag': 812,
 'getzed': 813,
 'summer': 814,
 'glad': 815,
 'fantastic': 816,
 'gap': 817,
 'king': 818,
 'em': 819,
 'cheap': 820,
 'across': 821,
 'less': 822,
 'near': 823,
 'water': 824,
 'style': 825,
 'different': 826,
 'wc': 827,
 'ldn': 828,
 'voice': 829,
 'mm': 830,
 'mistake': 831,
 'moment': 832,
 'rakhesh': 833,
 'custcare': 834,
 'immediately': 835,
 'merry': 836,
 'normal': 837,
 'somewhere': 838,
 'tonite': 839,
 'usual': 840,
 'deep': 841,
 'admirer': 842,
 'kick': 843,
 'street': 844,
 'sign': 845,
 'bathe': 846,
 'trust': 847,
 'waste': 848,
 'sony': 849,
 'del': 850,
 'quote': 851,
 'inform': 852,
 'representative': 853,
 'il': 854,
 'short': 855,
 'forever': 856,
 'hospital': 857,
 'oops': 858,
 'england': 859,
 'callertune': 860,
 'nah': 861,
 'cup': 862,
 'la': 863,
 'tear': 864,
 'sofa': 865,
 'colleagues': 866,
 'flag': 867,
 'thinkin': 868,
 'list': 869,
 'excellent': 870,
 'moral': 871,
 'tht': 872,
 'others': 873,
 'mode': 874,
 'mon': 875,
 'deliver': 876,
 'digital': 877,
 'hiya': 878,
 'wear': 879,
 'mo': 880,
 'iam': 881,
 'user': 882,
 'tampa': 883,
 'charity': 884,
 'comuk': 885,
 'ones': 886,
 'bid': 887,
 'norm': 888,
 'possible': 889,
 'bold': 890,
 'ho': 891,
 'pc': 892,
 'valentine': 893,
 'hurry': 894,
 'remind': 895,
 'self': 896,
 'fat': 897,
 'children': 898,
 'silent': 899,
 'meh': 900,
 'result': 901,
 'kinda': 902,
 'none': 903,
 'al': 904,
 'reference': 905,
 'bluetooth': 906,
 'urself': 907,
 'round': 908,
 'rcvd': 909,
 'valentines': 910,
 'access': 911,
 'record': 912,
 'cake': 913,
 'accept': 914,
 'sport': 915,
 'rise': 916,
 'tease': 917,
 'unless': 918,
 'throw': 919,
 'lover': 920,
 'ldew': 921,
 'cd': 922,
 'goodnight': 923,
 'flirt': 924,
 'lessons': 925,
 'appreciate': 926,
 'ive': 927,
 'mrt': 928,
 'dead': 929,
 'especially': 930,
 'lift': 931,
 'doesnt': 932,
 'completely': 933,
 'become': 934,
 'lect': 935,
 'lazy': 936,
 'lay': 937,
 'sunshine': 938,
 'flight': 939,
 'specially': 940,
 'boss': 941,
 'men': 942,
 'coffee': 943,
 'situation': 944,
 'ip': 945,
 'bx': 946,
 'ice': 947,
 'sick': 948,
 'mark': 949,
 'seriously': 950,
 'issue': 951,
 'mood': 952,
 'pix': 953,
 'er': 954,
 'wednesday': 955,
 'inside': 956,
 'south': 957,
 'arrive': 958,
 'bear': 959,
 'frens': 960,
 'vl': 961,
 'honey': 962,
 'hr': 963,
 'cute': 964,
 'black': 965,
 'movies': 966,
 'process': 967,
 'miracle': 968,
 'medical': 969,
 'gay': 970,
 'sale': 971,
 'travel': 972,
 'polys': 973,
 'moon': 974,
 'omg': 975,
 'slave': 976,
 'sing': 977,
 'space': 978,
 'library': 979,
 'idea': 980,
 'bedroom': 981,
 'tuesday': 982,
 'longer': 983,
 'alex': 984,
 'future': 985,
 'euro': 986,
 'ar': 987,
 'present': 988,
 'door': 989,
 'daddy': 990,
 'workin': 991,
 'finger': 992,
 'member': 993,
 'mp': 994,
 'realy': 995,
 'opinion': 996,
 'wx': 997,
 'thru': 998,
 'respond': 999,
 ...}

In [49]:
model.wv.similar_by_word('good')

[('night', 0.998808741569519),
 ('day', 0.9986789226531982),
 ('my', 0.9986007213592529),
 ('morning', 0.9985666871070862),
 ('its', 0.9984670281410217),
 ('of', 0.9984569549560547),
 ('well', 0.9984393119812012),
 ('all', 0.9984172582626343),
 ('should', 0.998387336730957),
 ('great', 0.9983511567115784)]

In [50]:
model.epochs

5

In [51]:
model.wv['good']

array([-0.26983684,  0.28634208,  0.06683651,  0.1496868 ,  0.12080589,
       -0.48033366,  0.22277506,  0.83949494, -0.4623963 , -0.24454232,
       -0.05222398, -0.46913102, -0.08441915,  0.09574383,  0.2423479 ,
       -0.07156371,  0.03249513, -0.40138268, -0.12896678, -0.74902546,
        0.06427221,  0.17358129,  0.33509398, -0.24483253, -0.05607488,
        0.05250363, -0.4004375 , -0.24144271, -0.3446223 ,  0.06429416,
        0.37710795,  0.00132907,  0.19074595, -0.24326347, -0.0122096 ,
        0.43692312,  0.01329467, -0.23699304, -0.21039152, -0.7333363 ,
        0.03402021, -0.27833834, -0.11551302,  0.08108362,  0.27208978,
       -0.08366965, -0.3678604 , -0.09536806,  0.24052064,  0.20031288,
        0.31804332, -0.45251915, -0.1723234 ,  0.07618318, -0.15406342,
        0.23653959,  0.25829056, -0.06962231, -0.50995916,  0.24543197,
        0.06773503,  0.0348357 ,  0.17432763, -0.14238006, -0.3985631 ,
        0.33992463,  0.24838327,  0.32735184, -0.641971  ,  0.46225756,
       -0.22178209,  0.15724255,  0.31201234,  0.04707589,  0.36017182,
        0.12940001, -0.00734599, -0.06744424, -0.3713844 , -0.10042133,
       -0.21366279,  0.09033536, -0.41089076,  0.56245756, -0.24637578,
        0.05719317,  0.06358279,  0.36367917,  0.5195641 ,  0.20405132,
        0.5892399 ,  0.3068226 ,  0.12679042,  0.12458804,  0.6480021 ,
        0.44867903,  0.18754858, -0.3131263 ,  0.21518108, -0.15790696],
      dtype=float32)

In [52]:
model.wv['good'].shape

(100,)

In [53]:
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [54]:
!pip install tqdm

Requirement already satisfied: tqdm in c:\users\hp\anaconda3\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from tqdm) (0.4.6)

In [55]:
from tqdm import tqdm

In [56]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5569 [00:00<?, ?it/s]

c:\Users\HP\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\HP\anaconda3\Lib\site-packages\numpy\_core\_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 5057.26it/s]

In [57]:
X

[array([-0.19033393,  0.21554631,  0.03387643,  0.08432529,  0.0814611 ,
        -0.34551477,  0.13152705,  0.5612902 , -0.33088964, -0.17135243,
        -0.05672189, -0.3349475 , -0.04045676,  0.05562684,  0.15834478,
        -0.06594842,  0.03369604, -0.276008  , -0.08534988, -0.5353388 ,
         0.06356161,  0.11452018,  0.21401699, -0.15542057, -0.05388319,
         0.04548482, -0.28465778, -0.15245257, -0.21956088,  0.06567686,
         0.26999474,  0.01121999,  0.10084259, -0.14632109, -0.01512662,
         0.2931678 , -0.0058529 , -0.17543425, -0.13158323, -0.5052467 ,
         0.02166648, -0.19522147, -0.06402542,  0.05456388,  0.17808025,
        -0.06936   , -0.22859088, -0.07231992,  0.15437706,  0.13036434,
         0.22348174, -0.33680114, -0.11049937,  0.03721336, -0.10005236,
         0.17892765,  0.17931145, -0.05374629, -0.35504195,  0.17462109,
         0.04174951,  0.01414453,  0.1311663 , -0.08635352, -0.26934007,
         0.2358733 ,  0.18662998,  0.23275429, -0.4169541 ,  0.30037448,
        -0.16378221,  0.07768583,  0.19666952,  0.02477506,  0.24263093,
         0.11654904, -0.03672637, -0.02143145, -0.25911197, -0.07814136,
        -0.14312913,  0.0508226 , -0.2810717 ,  0.38281864, -0.1361834 ,
         0.05075813,  0.05674887,  0.24718471,  0.36914963,  0.13818778,
         0.42674157,  0.1979378 ,  0.05836402,  0.08064307,  0.4526039 ,
         0.2806981 ,  0.13622706, -0.24627256,  0.14381641, -0.10962144],
       dtype=float32),
 array([-0.18080428,  0.20274475,  0.0296068 ,  0.07764257,  0.07246998,
        -0.32781845,  0.11480123,  0.52033794, -0.30136445, -0.15420282,
        -0.06597333, -0.31531566, -0.03831655,  0.05599001,  0.15140961,
        -0.07199959,  0.02454781, -0.25825074, -0.07538809, -0.48975188,
         0.06586384,  0.10626844,  0.20254481, -0.14773569, -0.0464874 ,
         0.04905088, -0.27451393, -0.14047867, -0.20596862,  0.05643076,
         0.25640473,  0.01392834,  0.09079865, -0.13176318, -0.01150297,
         0.266092  , -0.00725972, -0.16568607, -0.11724418, -0.46402764,
         0.01985132, -0.18223026, -0.06247352,  0.04073607,  0.14873324,
        -0.07116947, -0.21839152, -0.068734  ,  0.1462312 ,  0.12943923,
         0.20688672, -0.31905192, -0.08860896,  0.03574281, -0.08160941,
         0.18036625,  0.1580494 , -0.05106024, -0.33877605,  0.1649966 ,
         0.04474928,  0.01678991,  0.12369797, -0.07052709, -0.24740943,
         0.21356785,  0.17060143,  0.208817  , -0.38965434,  0.28148013,
        -0.1581764 ,  0.07469995,  0.18613012,  0.02442744,  0.21292958,
         0.10694063, -0.04253032, -0.02229722, -0.2377445 , -0.06346478,
        -0.1301896 ,  0.0448098 , -0.26745325,  0.36011165, -0.12510185,
         0.04434468,  0.04743296,  0.23341532,  0.34588403,  0.12469867,
         0.403762  ,  0.1786476 ,  0.05402811,  0.06891229,  0.4194087 ,
         0.26307368,  0.11896725, -0.23281762,  0.13456018, -0.10330726],
       dtype=float32),
 array([-0.22505139,  0.23939906,  0.03228942,  0.08651988,  0.10835537,
        -0.39909694,  0.11805752,  0.5843088 , -0.3601277 , -0.21018042,
        -0.0458467 , -0.37054536, -0.04955179,  0.02758927,  0.16196215,
        -0.06001304,  0.06928518, -0.31235597, -0.09246409, -0.58732367,
         0.04673076,  0.14917223,  0.20682368, -0.1586203 , -0.04826985,
         0.04201091, -0.31651288, -0.14687575, -0.22179164,  0.09525613,
         0.3218156 ,  0.03017014,  0.08426169, -0.13911647, -0.03350268,
         0.32818002, -0.03215081, -0.19279124, -0.12297397, -0.53735775,
         0.01958571, -0.20484008, -0.04703097,  0.04807471,  0.19498591,
        -0.05732471, -0.20460945, -0.06932336,  0.1369903 ,  0.11361659,
         0.2418475 , -0.40495002, -0.08207601,  0.05932181, -0.1399062 ,
         0.20642944,  0.18240175, -0.0609867 , -0.34659716,  0.22164303,
         0.04458843,  0.01703791,  0.14156112, -0.08222192, -0.28212863,
         0.2531331 ,  0.23576875,  0.2720504 , -0.4016545 ,  0.31520042,
        -0.17231847,  0.0246843 ,  0.19988051,  0.01885931,  0.26736814,
         0.11874342, -0.07011818,  0.00154099, -0.2659877 , -0.13157381,
        -0.14537764,  0.03923516, -0.30284676,  0.40860713, -0.12006088,
         0.09457888,  0.07841602,  0.23000945,  0.38880596,  0.12034738,
         0.46432316,  0.19529319,  0.03612697,  0.11457746,  0.4784982 ,
         0.2769469 ,  0.13881701, -0.32599315,  0.15554772, -0.11706846],
       dtype=float32),
 array([-0.2573401 ,  0.30323622,  0.04361198,  0.12218591,  0.10652817,
        -0.4690111 ,  0.19070789,  0.78136194, -0.45978355, -0.22614709,
        -0.08709432, -0.46311048, -0.05377913,  0.08752272,  0.2256674 ,
        -0.11082761,  0.03350465, -0.37629268, -0.12650006, -0.73705596,
         0.09437206,  0.14495732,  0.3172601 , -0.22317101, -0.0710691 ,
         0.07702934, -0.40456313, -0.21858594, -0.30296654,  0.07203882,
         0.3526903 ,  0.00452972,  0.14512585, -0.20653138, -0.01203028,
         0.38706514,  0.00229716, -0.24434921, -0.17672177, -0.6867308 ,
         0.0266793 , -0.27569714, -0.09313132,  0.08379918,  0.22914524,
        -0.10331804, -0.34111553, -0.112693  ,  0.22232172,  0.1973451 ,
         0.3073454 , -0.45750904, -0.15031311,  0.05214554, -0.1287235 ,
         0.24774389,  0.2467507 , -0.0639688 , -0.52075374,  0.24098532,
         0.06945406,  0.02221677,  0.18607844, -0.10918804, -0.36474672,
         0.32271245,  0.24052545,  0.30404952, -0.6001073 ,  0.41962054,
        -0.23813058,  0.13854143,  0.28475243,  0.0266821 ,  0.3164089 ,
         0.15418871, -0.04532942, -0.04135304, -0.3621959 , -0.08563076,
        -0.19561122,  0.0747393 , -0.39106628,  0.5293444 , -0.2023221 ,
         0.05300878,  0.0724384 ,  0.35847706,  0.5095797 ,  0.2014337 ,
         0.5918225 ,  0.2773154 ,  0.0920135 ,  0.09525859,  0.63947725,
         0.39071056,  0.19110356, -0.318919  ,  0.20402908, -0.15359959],
       dtype=float32),
 array([-2.15751231e-01,  2.48614892e-01,  3.76190841e-02,  9.60480198e-02,
         9.97969136e-02, -3.95730644e-01,  1.62036672e-01,  6.51848018e-01,
        -3.87716055e-01, -1.96505412e-01, -6.38496727e-02, -3.87008399e-01,
        -5.21465428e-02,  6.87069967e-02,  1.87777445e-01, -8.83709714e-02,
         3.48099656e-02, -3.17789912e-01, -1.09638281e-01, -6.22260988e-01,
         7.54775479e-02,  1.25926659e-01,  2.57691413e-01, -1.80392459e-01,
        -4.79633100e-02,  6.34339675e-02, -3.37542802e-01, -1.73532680e-01,
        -2.49628559e-01,  6.53940514e-02,  3.02971482e-01,  3.18130781e-03,
         1.12793386e-01, -1.78209856e-01, -9.33395606e-03,  3.38639826e-01,
        -3.38108308e-04, -1.97421864e-01, -1.50533274e-01, -5.73146164e-01,
         2.65978072e-02, -2.31118038e-01, -8.21349993e-02,  7.44475499e-02,
         1.98103949e-01, -7.96468630e-02, -2.76420325e-01, -9.37947854e-02,
         1.77984342e-01,  1.63200453e-01,  2.52563059e-01, -3.87698263e-01,
        -1.26543805e-01,  5.04779667e-02, -1.13491990e-01,  2.04296768e-01,
         2.08969727e-01, -5.98849803e-02, -4.23898578e-01,  2.02912107e-01,
         5.31950630e-02,  8.16404540e-03,  1.56522647e-01, -9.54478905e-02,
        -3.04190636e-01,  2.75662094e-01,  2.06587598e-01,  2.54324108e-01,
        -4.85127538e-01,  3.55255455e-01, -1.97623357e-01,  1.18626267e-01,
         2.33374298e-01,  2.17991546e-02,  2.68735915e-01,  1.29810065e-01,
        -3.25466432e-02, -3.46608348e-02, -3.01240355e-01, -8.14749599e-02,
        -1.66312099e-01,  6.46143481e-02, -3.27765554e-01,  4.35222268e-01,
        -1.64018586e-01,  5.00446856e-02,  6.79679811e-02,  2.92252719e-01,
         4.17741448e-01,  1.67979717e-01,  4.85025615e-01,  2.30704129e-01,
         7.16721043e-02,  8.58628154e-02,  5.30940950e-01,  3.24771315e-01,
         1.68128073e-01, -2.76037753e-01,  1.69328198e-01, -1.32387564e-01],
       dtype=float32),
 array([-0.23711255,  0.26774505,  0.03818038,  0.10672478,  0.1164716 ,
        -0.43716824,  0.16793765,  0.70242727, -0.41823974, -0.22144222,
        -0.06468122, -0.42047328, -0.05326953,  0.0666675 ,  0.20044404,
        -0.08749244,  0.04860344, -0.35140365, -0.11642379, -0.6756073 ,
         0.07463965,  0.14358068,  0.27457076, -0.19300142, -0.05078914,
         0.06052152, -0.3584327 , -0.18771173, -0.2726013 ,  0.08110432,
         0.34144655,  0.00781487,  0.12439672, -0.1916155 , -0.01810522,
         0.36940888, -0.0092098 , -0.21385294, -0.16428694, -0.62360764,
         0.02067536, -0.24390048, -0.08346213,  0.07488035,  0.21751605,
        -0.07948525, -0.28462753, -0.09588742,  0.18337914,  0.16549256,
         0.27545512, -0.42834222, -0.12809438,  0.05712486, -0.13402651,
         0.21814013,  0.21760783, -0.06670117, -0.44268018,  0.22902869,
         0.06067291,  0.01268157,  0.17459342, -0.10237431, -0.33571318,
         0.29821628,  0.23572375,  0.28529218, -0.51517576,  0.38522464,
        -0.20403154,  0.10696804,  0.2460704 ,  0.02210931,  0.29708716,
         0.13349973, -0.04147181, -0.02363368, -0.3224149 , -0.10598528,
        -0.18066342,  0.06657381, -0.35626104,  0.46787876, -0.17307022,
         0.06242404,  0.08087929,  0.30510604,  0.45566985,  0.1683898 ,
         0.5242033 ,  0.24541888,  0.07070984,  0.10234732,  0.56702894,
         0.34034792,  0.17190048, -0.31289163,  0.17837681, -0.13817286],
       dtype=float32),
 array([-0.23749116,  0.2698637 ,  0.04708111,  0.11483068,  0.10767675,
        -0.43597525,  0.18459383,  0.729653  , -0.42773598, -0.2162458 ,
        -0.06436601, -0.42584017, -0.0537859 ,  0.076107  ,  0.20811726,
        -0.08897618,  0.03977087, -0.3584204 , -0.12556008, -0.6958038 ,
         0.08437963,  0.13999553,  0.29586908, -0.20796612, -0.05578163,
         0.06877007, -0.36869353, -0.19715987, -0.28324533,  0.07312378,
         0.3359701 ,  0.00208875,  0.13597286, -0.2082286 , -0.01150959,
         0.36955357, -0.00098531, -0.2197247 , -0.1807908 , -0.64227545,
         0.02476803, -0.2555613 , -0.09483895,  0.08322964,  0.22578287,
        -0.0871248 , -0.30652833, -0.09985948,  0.20111619,  0.18051676,
         0.28162518, -0.42495698, -0.14545168,  0.05700405, -0.12892345,
         0.22131708,  0.22946785, -0.0658252 , -0.46590218,  0.22738147,
         0.06479183,  0.01255922,  0.18056461, -0.10563867, -0.3479412 ,
         0.31060928,  0.22672905,  0.2884685 , -0.54423827,  0.3966424 ,
        -0.21087857,  0.12826145,  0.260421  ,  0.0218154 ,  0.29769322,
         0.13519366, -0.03044152, -0.04139673, -0.3355917 , -0.09830642,
        -0.19094887,  0.07166042, -0.3694859 ,  0.48217878, -0.18599169,
         0.04739163,  0.07467091,  0.32750565,  0.46570134,  0.1864302 ,
         0.53793323,  0.25747806,  0.08356535,  0.09735186,  0.5901376 ,
         0.36242005,  0.18612956, -0.30253395,  0.18244627, -0.1464036 ],
       dtype=float32),
 array([-0.19599433,  0.22446948,  0.03113891,  0.08642952,  0.09519427,
        -0.3623469 ,  0.13653043,  0.5779113 , -0.34182125, -0.18404987,
        -0.03916116, -0.34471256, -0.0484202 ,  0.04130928,  0.15609214,
        -0.05596342,  0.05394527, -0.29428825, -0.09112941, -0.56214345,
         0.05311146,  0.12710269,  0.21916954, -0.15521276, -0.04851799,
         0.04331754, -0.29105175, -0.15457483, -0.22240764,  0.06951541,
         0.28320688,  0.01800295,  0.09705009, -0.16098207, -0.02017856,
         0.3037874 , -0.01325237, -0.18726203, -0.13242203, -0.51664925,
         0.01649311, -0.20052515, -0.05329979,  0.06352276,  0.19512445,
        -0.0583397 , -0.22478215, -0.06930251,  0.14881964,  0.1300171 ,
         0.22524314, -0.35771662, -0.10083741,  0.04550822, -0.1236451 ,
         0.17776118,  0.18360509, -0.05129841, -0.35365131,  0.19591925,
         0.04466252,  0.01150069,  0.13493176, -0.08293057, -0.27725905,
         0.24475908,  0.20008795,  0.25121984, -0.41017187,  0.31038958,
        -0.16456172,  0.06819271,  0.20318131,  0.02305923,  0.25353214,
         0.10759343, -0.04168943, -0.02024663, -0.26131874, -0.10038041,
        -0.14794432,  0.04914263, -0.28899685,  0.38306054, -0.13357237,
         0.06632283,  0.07056741,  0.24189645,  0.37349018,  0.13745321,
         0.43730292,  0.20330204,  0.05683285,  0.10285395,  0.46639973,
         0.28225616,  0.14092389, -0.2701326 ,  0.14244792, -0.11063377],
       dtype=float32),
 array([-0.23390417,  0.2481375 ,  0.03677519,  0.09581425,  0.11557323,
        -0.419437  ,  0.12249649,  0.62677634, -0.39523497, -0.21780503,
        -0.05010317, -0.3902808 , -0.05289676,  0.03836037,  0.17654242,
        -0.05611736,  0.07814756, -0.33219433, -0.10561807, -0.63093174,
         0.04761569,  0.16036306,  0.2335256 , -0.16536944, -0.04226886,
         0.0550267 , -0.3421655 , -0.16053376, -0.2445008 ,  0.09661905,
         0.33639997,  0.02859632,  0.09465191, -0.15307252, -0.03019575,
         0.34660912, -0.03952499, -0.21149056, -0.12284891, -0.5760201 ,
         0.01856289, -0.2234453 , -0.05037329,  0.0647762 ,  0.21191196,
        -0.06641146, -0.23561189, -0.07484324,  0.15367737,  0.1224677 ,
         0.24759865, -0.41760913, -0.09599026,  0.06840762, -0.14989072,
         0.20793399,  0.2015398 , -0.06102873, -0.37558287,  0.23449394,
         0.05296379,  0.01141962,  0.15706645, -0.08304347, -0.30630726,
         0.2702251 ,  0.24769077,  0.28681585, -0.43302053,  0.33987275,
        -0.1892606 ,  0.04004332,  0.2045705 ,  0.01238692,  0.28946912,
         0.12977973, -0.06322052,  0.00444017, -0.27587715, -0.14285494,
        -0.14197206,  0.05011274, -0.31623805,  0.43173704, -0.13511918,
         0.09239291,  0.08509833,  0.25889105,  0.41098887,  0.12346041,
         0.4961582 ,  0.21135417,  0.0442372 ,  0.12749663,  0.4987971 ,
         0.2998378 ,  0.15033618, -0.33327907,  0.16267614, -0.11140927],
       dtype=float32),
 array([-0.2519943 ,  0.2769872 ,  0.03250307,  0.10063899,  0.13159062,
        -0.46268052,  0.13916335,  0.68244725, -0.40837532, -0.249291  ,
        -0.0396557 , -0.43201703, -0.06352126,  0.025939  ,  0.18812746,
        -0.05627237,  0.08935908, -0.36319652, -0.1005235 , -0.68627024,
         0.0549641 ,  0.1670562 ,  0.23741631, -0.18209559, -0.06069995,
         0.04527291, -0.35504436, -0.17401281, -0.2565691 ,  0.10532968,
         0.37513825,  0.03740797,  0.09958135, -0.17173731, -0.03813714,
         0.3777526 , -0.03245272, -0.23042414, -0.14999455, -0.62538075,
         0.01805505, -0.24014111, -0.03844219,  0.06197288,  0.23977342,
        -0.07033934, -0.23138553, -0.06887941,  0.16596843,  0.13285902,
         0.2751665 , -0.46254554, -0.10064384,  0.06121495, -0.16469872,
         0.23483874,  0.21288574, -0.06874596, -0.3856446 ,  0.25195608,
         0.05043966,  0.01888908,  0.1643189 , -0.09119408, -0.33439073,
         0.29544848,  0.26579744,  0.32951754, -0.45738125,  0.36125985,
        -0.19328766,  0.0197075 ,  0.23148514,  0.02579041,  0.31626588,
         0.13459371, -0.07643835, -0.0066563 , -0.30795524, -0.1543519 ,
        -0.17173544,  0.04520953, -0.34791878,  0.47197846, -0.1326194 ,
         0.1135558 ,  0.10026008,  0.26978424,  0.46095312,  0.14090301,
         0.538519  ,  0.22882357,  0.04502515,  0.1509735 ,  0.5516201 ,
         0.32443187,  0.16001387, -0.37395462,  0.17112747, -0.14153396],
       dtype=float32),
 array([-2.11109862e-01,  2.37358123e-01,  3.59028317e-02,  9.41347331e-02,
         1.03290431e-01, -3.87948275e-01,  1.58262551e-01,  6.40345573e-01,
        -3.78986478e-01, -1.92621589e-01, -5.53988963e-02, -3.76190096e-01,
        -4.81806584e-02,  6.29854575e-02,  1.81201726e-01, -7.79847130e-02,
         3.84440757e-02, -3.15203726e-01, -1.09598905e-01, -6.12110496e-01,
         6.89380616e-02,  1.26840055e-01,  2.58738101e-01, -1.72588632e-01,
        -4.46063206e-02,  5.78784943e-02, -3.22830319e-01, -1.75060004e-01,
        -2.48967439e-01,  6.92991242e-02,  3.01064759e-01,  3.17708473e-04,
         1.15882002e-01, -1.76451340e-01, -1.14099989e-02,  3.28939229e-01,
        -5.01319440e-03, -1.92615032e-01, -1.48714334e-01, -5.64575434e-01,
         2.08338033e-02, -2.25356892e-01, -8.12115669e-02,  7.23647773e-02,
         1.95045352e-01, -7.21607432e-02, -2.65765756e-01, -9.26319808e-02,
         1.67022079e-01,  1.55218497e-01,  2.43593514e-01, -3.79557461e-01,
        -1.21425271e-01,  5.42038828e-02, -1.16869956e-01,  1.94859236e-01,
         2.03329131e-01, -5.98775335e-02, -4.08230096e-01,  2.04438627e-01,
         5.80420233e-02,  7.89259747e-03,  1.57382458e-01, -9.27155614e-02,
        -3.07159871e-01,  2.68991441e-01,  2.08859950e-01,  2.49783337e-01,
        -4.74955201e-01,  3.51948589e-01, -1.88558176e-01,  1.07161410e-01,
         2.22164959e-01,  1.82735156e-02,  2.65205920e-01,  1.19370222e-01,
        -3.00723538e-02, -2.38490198e-02, -2.97723055e-01, -9.13661420e-02,
        -1.59699619e-01,  6.52810857e-02, -3.19427937e-01,  4.21860009e-01,
        -1.65576518e-01,  5.15178330e-02,  6.88542351e-02,  2.83314675e-01,
         4.03502315e-01,  1.54563680e-01,  4.74199176e-01,  2.22687989e-01,
         7.15300515e-02,  8.97805020e-02,  5.18241465e-01,  3.11699033e-01,
         1.59793332e-01, -2.74208575e-01,  1.60815448e-01, -1.26050964e-01],
       dtype=float32),
 array([-0.2617619 ,  0.2766219 ,  0.04078227,  0.10315628,  0.13070896,
        -0.4611036 ,  0.14102842,  0.6808578 , -0.41933537, -0.24400268,
        -0.05500767, -0.42399108, -0.05771862,  0.03093111,  0.18860525,
        -0.06682014,  0.08321171, -0.36281204, -0.10769205, -0.6824581 ,
         0.05109255,  0.18061513,  0.24917048, -0.18072838, -0.0519092 ,
         0.04888172, -0.3692711 , -0.17383835, -0.2637261 ,  0.11089242,
         0.37178957,  0.03076115,  0.09822001, -0.16518952, -0.03790994,
         0.3844499 , -0.04185809, -0.22886926, -0.14095256, -0.6250055 ,
         0.02468899, -0.24413249, -0.05736458,  0.0611667 ,  0.2262357 ,
        -0.06689968, -0.23995686, -0.08524129,  0.15716402,  0.1290564 ,
         0.2788132 , -0.4717429 , -0.09235695,  0.07456546, -0.1699346 ,
         0.235022  ,  0.21094722, -0.07126166, -0.40568006,  0.25792944,
         0.0552738 ,  0.01462234,  0.16531973, -0.09452052, -0.32336837,
         0.29751375,  0.27455246,  0.3131923 , -0.46903768,  0.3708167 ,
        -0.19936143,  0.03744956,  0.23574975,  0.02090777,  0.31386143,
         0.1382789 , -0.08171809,  0.00483755, -0.31023   , -0.1575548 ,
        -0.1648764 ,  0.0441103 , -0.35165718,  0.473811  , -0.14364898,
         0.10854249,  0.09288558,  0.27031922,  0.4464597 ,  0.13665788,
         0.54188883,  0.2280372 ,  0.04173933,  0.13312468,  0.55486935,
         0.31911585,  0.16372576, -0.37994653,  0.181374  , -0.13547722],
       dtype=float32),
 array([-0.27795693,  0.2955072 ,  0.04105591,  0.10514176,  0.13702673,
        -0.49477994,  0.14877549,  0.72992915, -0.45278695, -0.2609879 ,
        -0.0531917 , -0.45766962, -0.06249413,  0.03196894,  0.19906157,
        -0.07209305,  0.09367695, -0.39188978, -0.11438623, -0.73403764,
         0.05544742,  0.19167349,  0.26014742, -0.19603571, -0.05947269,
         0.04951202, -0.3902031 , -0.18529148, -0.27999216,  0.11439415,
         0.39965463,  0.03462616,  0.10286666, -0.1813167 , -0.04516312,
         0.41339383, -0.04489138, -0.24702534, -0.15276639, -0.67440623,
         0.02526082, -0.258322  , -0.05432852,  0.06747828,  0.2530633 ,
        -0.07235601, -0.26020762, -0.08568062,  0.1674596 ,  0.13835175,
         0.29710665, -0.4997554 , -0.10226545,  0.0740285 , -0.18427807,
         0.24790603,  0.22702889, -0.07941145, -0.43151072,  0.27515772,
         0.05585276,  0.01875802,  0.1816551 , -0.1026289 , -0.34967044,
         0.3172678 ,  0.29351687,  0.3423159 , -0.5013954 ,  0.39189506,
        -0.21405137,  0.03133562,  0.2436789 ,  0.02090811,  0.34077114,
         0.14843182, -0.08329788,  0.00440154, -0.32669464, -0.1645286 ,
        -0.17500535,  0.05306153, -0.37708417,  0.5081178 , -0.15148005,

In [58]:
len(X)

5569

In [61]:
X

[array([-0.19033393,  0.21554631,  0.03387643,  0.08432529,  0.0814611 ,
        -0.34551477,  0.13152705,  0.5612902 , -0.33088964, -0.17135243,
        -0.05672189, -0.3349475 , -0.04045676,  0.05562684,  0.15834478,
        -0.06594842,  0.03369604, -0.276008  , -0.08534988, -0.5353388 ,
         0.06356161,  0.11452018,  0.21401699, -0.15542057, -0.05388319,
         0.04548482, -0.28465778, -0.15245257, -0.21956088,  0.06567686,
         0.26999474,  0.01121999,  0.10084259, -0.14632109, -0.01512662,
         0.2931678 , -0.0058529 , -0.17543425, -0.13158323, -0.5052467 ,
         0.02166648, -0.19522147, -0.06402542,  0.05456388,  0.17808025,
        -0.06936   , -0.22859088, -0.07231992,  0.15437706,  0.13036434,
         0.22348174, -0.33680114, -0.11049937,  0.03721336, -0.10005236,
         0.17892765,  0.17931145, -0.05374629, -0.35504195,  0.17462109,
         0.04174951,  0.01414453,  0.1311663 , -0.08635352, -0.26934007,
         0.2358733 ,  0.18662998,  0.23275429, -0.4169541 ,  0.30037448,
        -0.16378221,  0.07768583,  0.19666952,  0.02477506,  0.24263093,
         0.11654904, -0.03672637, -0.02143145, -0.25911197, -0.07814136,
        -0.14312913,  0.0508226 , -0.2810717 ,  0.38281864, -0.1361834 ,
         0.05075813,  0.05674887,  0.24718471,  0.36914963,  0.13818778,
         0.42674157,  0.1979378 ,  0.05836402,  0.08064307,  0.4526039 ,
         0.2806981 ,  0.13622706, -0.24627256,  0.14381641, -0.10962144],
       dtype=float32),
 array([-0.18080428,  0.20274475,  0.0296068 ,  0.07764257,  0.07246998,
        -0.32781845,  0.11480123,  0.52033794, -0.30136445, -0.15420282,
        -0.06597333, -0.31531566, -0.03831655,  0.05599001,  0.15140961,
        -0.07199959,  0.02454781, -0.25825074, -0.07538809, -0.48975188,
         0.06586384,  0.10626844,  0.20254481, -0.14773569, -0.0464874 ,
         0.04905088, -0.27451393, -0.14047867, -0.20596862,  0.05643076,
         0.25640473,  0.01392834,  0.09079865, -0.13176318, -0.01150297,
         0.266092  , -0.00725972, -0.16568607, -0.11724418, -0.46402764,
         0.01985132, -0.18223026, -0.06247352,  0.04073607,  0.14873324,
        -0.07116947, -0.21839152, -0.068734  ,  0.1462312 ,  0.12943923,
         0.20688672, -0.31905192, -0.08860896,  0.03574281, -0.08160941,
         0.18036625,  0.1580494 , -0.05106024, -0.33877605,  0.1649966 ,
         0.04474928,  0.01678991,  0.12369797, -0.07052709, -0.24740943,
         0.21356785,  0.17060143,  0.208817  , -0.38965434,  0.28148013,
        -0.1581764 ,  0.07469995,  0.18613012,  0.02442744,  0.21292958,
         0.10694063, -0.04253032, -0.02229722, -0.2377445 , -0.06346478,
        -0.1301896 ,  0.0448098 , -0.26745325,  0.36011165, -0.12510185,
         0.04434468,  0.04743296,  0.23341532,  0.34588403,  0.12469867,
         0.403762  ,  0.1786476 ,  0.05402811,  0.06891229,  0.4194087 ,
         0.26307368,  0.11896725, -0.23281762,  0.13456018, -0.10330726],
       dtype=float32),
 array([-0.22505139,  0.23939906,  0.03228942,  0.08651988,  0.10835537,
        -0.39909694,  0.11805752,  0.5843088 , -0.3601277 , -0.21018042,
        -0.0458467 , -0.37054536, -0.04955179,  0.02758927,  0.16196215,
        -0.06001304,  0.06928518, -0.31235597, -0.09246409, -0.58732367,
         0.04673076,  0.14917223,  0.20682368, -0.1586203 , -0.04826985,
         0.04201091, -0.31651288, -0.14687575, -0.22179164,  0.09525613,
         0.3218156 ,  0.03017014,  0.08426169, -0.13911647, -0.03350268,
         0.32818002, -0.03215081, -0.19279124, -0.12297397, -0.53735775,
         0.01958571, -0.20484008, -0.04703097,  0.04807471,  0.19498591,
        -0.05732471, -0.20460945, -0.06932336,  0.1369903 ,  0.11361659,
         0.2418475 , -0.40495002, -0.08207601,  0.05932181, -0.1399062 ,
         0.20642944,  0.18240175, -0.0609867 , -0.34659716,  0.22164303,
         0.04458843,  0.01703791,  0.14156112, -0.08222192, -0.28212863,
         0.2531331 ,  0.23576875,  0.2720504 , -0.4016545 ,  0.31520042,
        -0.17231847,  0.0246843 ,  0.19988051,  0.01885931,  0.26736814,
         0.11874342, -0.07011818,  0.00154099, -0.2659877 , -0.13157381,
        -0.14537764,  0.03923516, -0.30284676,  0.40860713, -0.12006088,
         0.09457888,  0.07841602,  0.23000945,  0.38880596,  0.12034738,
         0.46432316,  0.19529319,  0.03612697,  0.11457746,  0.4784982 ,
         0.2769469 ,  0.13881701, -0.32599315,  0.15554772, -0.11706846],
       dtype=float32),
 array([-0.2573401 ,  0.30323622,  0.04361198,  0.12218591,  0.10652817,
        -0.4690111 ,  0.19070789,  0.78136194, -0.45978355, -0.22614709,
        -0.08709432, -0.46311048, -0.05377913,  0.08752272,  0.2256674 ,
        -0.11082761,  0.03350465, -0.37629268, -0.12650006, -0.73705596,
         0.09437206,  0.14495732,  0.3172601 , -0.22317101, -0.0710691 ,
         0.07702934, -0.40456313, -0.21858594, -0.30296654,  0.07203882,
         0.3526903 ,  0.00452972,  0.14512585, -0.20653138, -0.01203028,
         0.38706514,  0.00229716, -0.24434921, -0.17672177, -0.6867308 ,
         0.0266793 , -0.27569714, -0.09313132,  0.08379918,  0.22914524,
        -0.10331804, -0.34111553, -0.112693  ,  0.22232172,  0.1973451 ,
         0.3073454 , -0.45750904, -0.15031311,  0.05214554, -0.1287235 ,
         0.24774389,  0.2467507 , -0.0639688 , -0.52075374,  0.24098532,
         0.06945406,  0.02221677,  0.18607844, -0.10918804, -0.36474672,
         0.32271245,  0.24052545,  0.30404952, -0.6001073 ,  0.41962054,
        -0.23813058,  0.13854143,  0.28475243,  0.0266821 ,  0.3164089 ,
         0.15418871, -0.04532942, -0.04135304, -0.3621959 , -0.08563076,
        -0.19561122,  0.0747393 , -0.39106628,  0.5293444 , -0.2023221 ,
         0.05300878,  0.0724384 ,  0.35847706,  0.5095797 ,  0.2014337 ,
         0.5918225 ,  0.2773154 ,  0.0920135 ,  0.09525859,  0.63947725,
         0.39071056,  0.19110356, -0.318919  ,  0.20402908, -0.15359959],
       dtype=float32),
 array([-2.15751231e-01,  2.48614892e-01,  3.76190841e-02,  9.60480198e-02,
         9.97969136e-02, -3.95730644e-01,  1.62036672e-01,  6.51848018e-01,
        -3.87716055e-01, -1.96505412e-01, -6.38496727e-02, -3.87008399e-01,
        -5.21465428e-02,  6.87069967e-02,  1.87777445e-01, -8.83709714e-02,
         3.48099656e-02, -3.17789912e-01, -1.09638281e-01, -6.22260988e-01,
         7.54775479e-02,  1.25926659e-01,  2.57691413e-01, -1.80392459e-01,
        -4.79633100e-02,  6.34339675e-02, -3.37542802e-01, -1.73532680e-01,
        -2.49628559e-01,  6.53940514e-02,  3.02971482e-01,  3.18130781e-03,
         1.12793386e-01, -1.78209856e-01, -9.33395606e-03,  3.38639826e-01,
        -3.38108308e-04, -1.97421864e-01, -1.50533274e-01, -5.73146164e-01,
         2.65978072e-02, -2.31118038e-01, -8.21349993e-02,  7.44475499e-02,
         1.98103949e-01, -7.96468630e-02, -2.76420325e-01, -9.37947854e-02,
         1.77984342e-01,  1.63200453e-01,  2.52563059e-01, -3.87698263e-01,
        -1.26543805e-01,  5.04779667e-02, -1.13491990e-01,  2.04296768e-01,
         2.08969727e-01, -5.98849803e-02, -4.23898578e-01,  2.02912107e-01,
         5.31950630e-02,  8.16404540e-03,  1.56522647e-01, -9.54478905e-02,
        -3.04190636e-01,  2.75662094e-01,  2.06587598e-01,  2.54324108e-01,
        -4.85127538e-01,  3.55255455e-01, -1.97623357e-01,  1.18626267e-01,
         2.33374298e-01,  2.17991546e-02,  2.68735915e-01,  1.29810065e-01,
        -3.25466432e-02, -3.46608348e-02, -3.01240355e-01, -8.14749599e-02,
        -1.66312099e-01,  6.46143481e-02, -3.27765554e-01,  4.35222268e-01,
        -1.64018586e-01,  5.00446856e-02,  6.79679811e-02,  2.92252719e-01,
         4.17741448e-01,  1.67979717e-01,  4.85025615e-01,  2.30704129e-01,
         7.16721043e-02,  8.58628154e-02,  5.30940950e-01,  3.24771315e-01,
         1.68128073e-01, -2.76037753e-01,  1.69328198e-01, -1.32387564e-01],
       dtype=float32),
 array([-0.23711255,  0.26774505,  0.03818038,  0.10672478,  0.1164716 ,
        -0.43716824,  0.16793765,  0.70242727, -0.41823974, -0.22144222,
        -0.06468122, -0.42047328, -0.05326953,  0.0666675 ,  0.20044404,
        -0.08749244,  0.04860344, -0.35140365, -0.11642379, -0.6756073 ,
         0.07463965,  0.14358068,  0.27457076, -0.19300142, -0.05078914,
         0.06052152, -0.3584327 , -0.18771173, -0.2726013 ,  0.08110432,
         0.34144655,  0.00781487,  0.12439672, -0.1916155 , -0.01810522,
         0.36940888, -0.0092098 , -0.21385294, -0.16428694, -0.62360764,
         0.02067536, -0.24390048, -0.08346213,  0.07488035,  0.21751605,
        -0.07948525, -0.28462753, -0.09588742,  0.18337914,  0.16549256,
         0.27545512, -0.42834222, -0.12809438,  0.05712486, -0.13402651,
         0.21814013,  0.21760783, -0.06670117, -0.44268018,  0.22902869,
         0.06067291,  0.01268157,  0.17459342, -0.10237431, -0.33571318,
         0.29821628,  0.23572375,  0.28529218, -0.51517576,  0.38522464,
        -0.20403154,  0.10696804,  0.2460704 ,  0.02210931,  0.29708716,
         0.13349973, -0.04147181, -0.02363368, -0.3224149 , -0.10598528,
        -0.18066342,  0.06657381, -0.35626104,  0.46787876, -0.17307022,
         0.06242404,  0.08087929,  0.30510604,  0.45566985,  0.1683898 ,
         0.5242033 ,  0.24541888,  0.07070984,  0.10234732,  0.56702894,
         0.34034792,  0.17190048, -0.31289163,  0.17837681, -0.13817286],
       dtype=float32),
 array([-0.23749116,  0.2698637 ,  0.04708111,  0.11483068,  0.10767675,
        -0.43597525,  0.18459383,  0.729653  , -0.42773598, -0.2162458 ,
        -0.06436601, -0.42584017, -0.0537859 ,  0.076107  ,  0.20811726,
        -0.08897618,  0.03977087, -0.3584204 , -0.12556008, -0.6958038 ,
         0.08437963,  0.13999553,  0.29586908, -0.20796612, -0.05578163,
         0.06877007, -0.36869353, -0.19715987, -0.28324533,  0.07312378,
         0.3359701 ,  0.00208875,  0.13597286, -0.2082286 , -0.01150959,
         0.36955357, -0.00098531, -0.2197247 , -0.1807908 , -0.64227545,
         0.02476803, -0.2555613 , -0.09483895,  0.08322964,  0.22578287,
        -0.0871248 , -0.30652833, -0.09985948,  0.20111619,  0.18051676,
         0.28162518, -0.42495698, -0.14545168,  0.05700405, -0.12892345,
         0.22131708,  0.22946785, -0.0658252 , -0.46590218,  0.22738147,
         0.06479183,  0.01255922,  0.18056461, -0.10563867, -0.3479412 ,
         0.31060928,  0.22672905,  0.2884685 , -0.54423827,  0.3966424 ,
        -0.21087857,  0.12826145,  0.260421  ,  0.0218154 ,  0.29769322,
         0.13519366, -0.03044152, -0.04139673, -0.3355917 , -0.09830642,
        -0.19094887,  0.07166042, -0.3694859 ,  0.48217878, -0.18599169,
         0.04739163,  0.07467091,  0.32750565,  0.46570134,  0.1864302 ,
         0.53793323,  0.25747806,  0.08356535,  0.09735186,  0.5901376 ,
         0.36242005,  0.18612956, -0.30253395,  0.18244627, -0.1464036 ],
       dtype=float32),
 array([-0.19599433,  0.22446948,  0.03113891,  0.08642952,  0.09519427,
        -0.3623469 ,  0.13653043,  0.5779113 , -0.34182125, -0.18404987,
        -0.03916116, -0.34471256, -0.0484202 ,  0.04130928,  0.15609214,
        -0.05596342,  0.05394527, -0.29428825, -0.09112941, -0.56214345,
         0.05311146,  0.12710269,  0.21916954, -0.15521276, -0.04851799,
         0.04331754, -0.29105175, -0.15457483, -0.22240764,  0.06951541,
         0.28320688,  0.01800295,  0.09705009, -0.16098207, -0.02017856,
         0.3037874 , -0.01325237, -0.18726203, -0.13242203, -0.51664925,
         0.01649311, -0.20052515, -0.05329979,  0.06352276,  0.19512445,
        -0.0583397 , -0.22478215, -0.06930251,  0.14881964,  0.1300171 ,
         0.22524314, -0.35771662, -0.10083741,  0.04550822, -0.1236451 ,
         0.17776118,  0.18360509, -0.05129841, -0.35365131,  0.19591925,
         0.04466252,  0.01150069,  0.13493176, -0.08293057, -0.27725905,
         0.24475908,  0.20008795,  0.25121984, -0.41017187,  0.31038958,
        -0.16456172,  0.06819271,  0.20318131,  0.02305923,  0.25353214,
         0.10759343, -0.04168943, -0.02024663, -0.26131874, -0.10038041,
        -0.14794432,  0.04914263, -0.28899685,  0.38306054, -0.13357237,
         0.06632283,  0.07056741,  0.24189645,  0.37349018,  0.13745321,
         0.43730292,  0.20330204,  0.05683285,  0.10285395,  0.46639973,
         0.28225616,  0.14092389, -0.2701326 ,  0.14244792, -0.11063377],
       dtype=float32),
 array([-0.23390417,  0.2481375 ,  0.03677519,  0.09581425,  0.11557323,
        -0.419437  ,  0.12249649,  0.62677634, -0.39523497, -0.21780503,
        -0.05010317, -0.3902808 , -0.05289676,  0.03836037,  0.17654242,
        -0.05611736,  0.07814756, -0.33219433, -0.10561807, -0.63093174,
         0.04761569,  0.16036306,  0.2335256 , -0.16536944, -0.04226886,
         0.0550267 , -0.3421655 , -0.16053376, -0.2445008 ,  0.09661905,
         0.33639997,  0.02859632,  0.09465191, -0.15307252, -0.03019575,
         0.34660912, -0.03952499, -0.21149056, -0.12284891, -0.5760201 ,
         0.01856289, -0.2234453 , -0.05037329,  0.0647762 ,  0.21191196,
        -0.06641146, -0.23561189, -0.07484324,  0.15367737,  0.1224677 ,
         0.24759865, -0.41760913, -0.09599026,  0.06840762, -0.14989072,
         0.20793399,  0.2015398 , -0.06102873, -0.37558287,  0.23449394,
         0.05296379,  0.01141962,  0.15706645, -0.08304347, -0.30630726,
         0.2702251 ,  0.24769077,  0.28681585, -0.43302053,  0.33987275,
        -0.1892606 ,  0.04004332,  0.2045705 ,  0.01238692,  0.28946912,
         0.12977973, -0.06322052,  0.00444017, -0.27587715, -0.14285494,
        -0.14197206,  0.05011274, -0.31623805,  0.43173704, -0.13511918,
         0.09239291,  0.08509833,  0.25889105,  0.41098887,  0.12346041,
         0.4961582 ,  0.21135417,  0.0442372 ,  0.12749663,  0.4987971 ,
         0.2998378 ,  0.15033618, -0.33327907,  0.16267614, -0.11140927],
       dtype=float32),
 array([-0.2519943 ,  0.2769872 ,  0.03250307,  0.10063899,  0.13159062,
        -0.46268052,  0.13916335,  0.68244725, -0.40837532, -0.249291  ,
        -0.0396557 , -0.43201703, -0.06352126,  0.025939  ,  0.18812746,
        -0.05627237,  0.08935908, -0.36319652, -0.1005235 , -0.68627024,
         0.0549641 ,  0.1670562 ,  0.23741631, -0.18209559, -0.06069995,
         0.04527291, -0.35504436, -0.17401281, -0.2565691 ,  0.10532968,
         0.37513825,  0.03740797,  0.09958135, -0.17173731, -0.03813714,
         0.3777526 , -0.03245272, -0.23042414, -0.14999455, -0.62538075,
         0.01805505, -0.24014111, -0.03844219,  0.06197288,  0.23977342,
        -0.07033934, -0.23138553, -0.06887941,  0.16596843,  0.13285902,
         0.2751665 , -0.46254554, -0.10064384,  0.06121495, -0.16469872,
         0.23483874,  0.21288574, -0.06874596, -0.3856446 ,  0.25195608,
         0.05043966,  0.01888908,  0.1643189 , -0.09119408, -0.33439073,
         0.29544848,  0.26579744,  0.32951754, -0.45738125,  0.36125985,
        -0.19328766,  0.0197075 ,  0.23148514,  0.02579041,  0.31626588,
         0.13459371, -0.07643835, -0.0066563 , -0.30795524, -0.1543519 ,
        -0.17173544,  0.04520953, -0.34791878,  0.47197846, -0.1326194 ,
         0.1135558 ,  0.10026008,  0.26978424,  0.46095312,  0.14090301,
         0.538519  ,  0.22882357,  0.04502515,  0.1509735 ,  0.5516201 ,
         0.32443187,  0.16001387, -0.37395462,  0.17112747, -0.14153396],
       dtype=float32),
 array([-2.11109862e-01,  2.37358123e-01,  3.59028317e-02,  9.41347331e-02,
         1.03290431e-01, -3.87948275e-01,  1.58262551e-01,  6.40345573e-01,
        -3.78986478e-01, -1.92621589e-01, -5.53988963e-02, -3.76190096e-01,
        -4.81806584e-02,  6.29854575e-02,  1.81201726e-01, -7.79847130e-02,
         3.84440757e-02, -3.15203726e-01, -1.09598905e-01, -6.12110496e-01,
         6.89380616e-02,  1.26840055e-01,  2.58738101e-01, -1.72588632e-01,
        -4.46063206e-02,  5.78784943e-02, -3.22830319e-01, -1.75060004e-01,
        -2.48967439e-01,  6.92991242e-02,  3.01064759e-01,  3.17708473e-04,
         1.15882002e-01, -1.76451340e-01, -1.14099989e-02,  3.28939229e-01,
        -5.01319440e-03, -1.92615032e-01, -1.48714334e-01, -5.64575434e-01,
         2.08338033e-02, -2.25356892e-01, -8.12115669e-02,  7.23647773e-02,
         1.95045352e-01, -7.21607432e-02, -2.65765756e-01, -9.26319808e-02,
         1.67022079e-01,  1.55218497e-01,  2.43593514e-01, -3.79557461e-01,
        -1.21425271e-01,  5.42038828e-02, -1.16869956e-01,  1.94859236e-01,
         2.03329131e-01, -5.98775335e-02, -4.08230096e-01,  2.04438627e-01,
         5.80420233e-02,  7.89259747e-03,  1.57382458e-01, -9.27155614e-02,
        -3.07159871e-01,  2.68991441e-01,  2.08859950e-01,  2.49783337e-01,
        -4.74955201e-01,  3.51948589e-01, -1.88558176e-01,  1.07161410e-01,
         2.22164959e-01,  1.82735156e-02,  2.65205920e-01,  1.19370222e-01,
        -3.00723538e-02, -2.38490198e-02, -2.97723055e-01, -9.13661420e-02,
        -1.59699619e-01,  6.52810857e-02, -3.19427937e-01,  4.21860009e-01,
        -1.65576518e-01,  5.15178330e-02,  6.88542351e-02,  2.83314675e-01,
         4.03502315e-01,  1.54563680e-01,  4.74199176e-01,  2.22687989e-01,
         7.15300515e-02,  8.97805020e-02,  5.18241465e-01,  3.11699033e-01,
         1.59793332e-01, -2.74208575e-01,  1.60815448e-01, -1.26050964e-01],
       dtype=float32),
 array([-0.2617619 ,  0.2766219 ,  0.04078227,  0.10315628,  0.13070896,
        -0.4611036 ,  0.14102842,  0.6808578 , -0.41933537, -0.24400268,
        -0.05500767, -0.42399108, -0.05771862,  0.03093111,  0.18860525,
        -0.06682014,  0.08321171, -0.36281204, -0.10769205, -0.6824581 ,
         0.05109255,  0.18061513,  0.24917048, -0.18072838, -0.0519092 ,
         0.04888172, -0.3692711 , -0.17383835, -0.2637261 ,  0.11089242,
         0.37178957,  0.03076115,  0.09822001, -0.16518952, -0.03790994,
         0.3844499 , -0.04185809, -0.22886926, -0.14095256, -0.6250055 ,
         0.02468899, -0.24413249, -0.05736458,  0.0611667 ,  0.2262357 ,
        -0.06689968, -0.23995686, -0.08524129,  0.15716402,  0.1290564 ,
         0.2788132 , -0.4717429 , -0.09235695,  0.07456546, -0.1699346 ,
         0.235022  ,  0.21094722, -0.07126166, -0.40568006,  0.25792944,
         0.0552738 ,  0.01462234,  0.16531973, -0.09452052, -0.32336837,
         0.29751375,  0.27455246,  0.3131923 , -0.46903768,  0.3708167 ,
        -0.19936143,  0.03744956,  0.23574975,  0.02090777,  0.31386143,
         0.1382789 , -0.08171809,  0.00483755, -0.31023   , -0.1575548 ,
        -0.1648764 ,  0.0441103 , -0.35165718,  0.473811  , -0.14364898,
         0.10854249,  0.09288558,  0.27031922,  0.4464597 ,  0.13665788,
         0.54188883,  0.2280372 ,  0.04173933,  0.13312468,  0.55486935,
         0.31911585,  0.16372576, -0.37994653,  0.181374  , -0.13547722],
       dtype=float32),
 array([-0.27795693,  0.2955072 ,  0.04105591,  0.10514176,  0.13702673,
        -0.49477994,  0.14877549,  0.72992915, -0.45278695, -0.2609879 ,
        -0.0531917 , -0.45766962, -0.06249413,  0.03196894,  0.19906157,
        -0.07209305,  0.09367695, -0.39188978, -0.11438623, -0.73403764,
         0.05544742,  0.19167349,  0.26014742, -0.19603571, -0.05947269,
         0.04951202, -0.3902031 , -0.18529148, -0.27999216,  0.11439415,
         0.39965463,  0.03462616,  0.10286666, -0.1813167 , -0.04516312,
         0.41339383, -0.04489138, -0.24702534, -0.15276639, -0.67440623,
         0.02526082, -0.258322  , -0.05432852,  0.06747828,  0.2530633 ,
        -0.07235601, -0.26020762, -0.08568062,  0.1674596 ,  0.13835175,
         0.29710665, -0.4997554 , -0.10226545,  0.0740285 , -0.18427807,
         0.24790603,  0.22702889, -0.07941145, -0.43151072,  0.27515772,
         0.05585276,  0.01875802,  0.1816551 , -0.1026289 , -0.34967044,
         0.3172678 ,  0.29351687,  0.3423159 , -0.5013954 ,  0.39189506,
        -0.21405137,  0.03133562,  0.2436789 ,  0.02090811,  0.34077114,
         0.14843182, -0.08329788,  0.00440154, -0.32669464, -0.1645286 ,
        -0.17500535,  0.05306153, -0.37708417,  0.5081178 , -0.15148005,

In [68]:
len(X)

5569

In [70]:
df['label'].shape

(5572,)

In [71]:
y = df[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values

In [73]:
y.shape

(5569,)

In [74]:
X

[array([-0.19033393,  0.21554631,  0.03387643,  0.08432529,  0.0814611 ,
        -0.34551477,  0.13152705,  0.5612902 , -0.33088964, -0.17135243,
        -0.05672189, -0.3349475 , -0.04045676,  0.05562684,  0.15834478,
        -0.06594842,  0.03369604, -0.276008  , -0.08534988, -0.5353388 ,
         0.06356161,  0.11452018,  0.21401699, -0.15542057, -0.05388319,
         0.04548482, -0.28465778, -0.15245257, -0.21956088,  0.06567686,
         0.26999474,  0.01121999,  0.10084259, -0.14632109, -0.01512662,
         0.2931678 , -0.0058529 , -0.17543425, -0.13158323, -0.5052467 ,
         0.02166648, -0.19522147, -0.06402542,  0.05456388,  0.17808025,
        -0.06936   , -0.22859088, -0.07231992,  0.15437706,  0.13036434,
         0.22348174, -0.33680114, -0.11049937,  0.03721336, -0.10005236,
         0.17892765,  0.17931145, -0.05374629, -0.35504195,  0.17462109,
         0.04174951,  0.01414453,  0.1311663 , -0.08635352, -0.26934007,
         0.2358733 ,  0.18662998,  0.23275429, -0.4169541 ,  0.30037448,
        -0.16378221,  0.07768583,  0.19666952,  0.02477506,  0.24263093,
         0.11654904, -0.03672637, -0.02143145, -0.25911197, -0.07814136,
        -0.14312913,  0.0508226 , -0.2810717 ,  0.38281864, -0.1361834 ,
         0.05075813,  0.05674887,  0.24718471,  0.36914963,  0.13818778,
         0.42674157,  0.1979378 ,  0.05836402,  0.08064307,  0.4526039 ,
         0.2806981 ,  0.13622706, -0.24627256,  0.14381641, -0.10962144],
       dtype=float32),
 array([-0.18080428,  0.20274475,  0.0296068 ,  0.07764257,  0.07246998,
        -0.32781845,  0.11480123,  0.52033794, -0.30136445, -0.15420282,
        -0.06597333, -0.31531566, -0.03831655,  0.05599001,  0.15140961,
        -0.07199959,  0.02454781, -0.25825074, -0.07538809, -0.48975188,
         0.06586384,  0.10626844,  0.20254481, -0.14773569, -0.0464874 ,
         0.04905088, -0.27451393, -0.14047867, -0.20596862,  0.05643076,
         0.25640473,  0.01392834,  0.09079865, -0.13176318, -0.01150297,
         0.266092  , -0.00725972, -0.16568607, -0.11724418, -0.46402764,
         0.01985132, -0.18223026, -0.06247352,  0.04073607,  0.14873324,
        -0.07116947, -0.21839152, -0.068734  ,  0.1462312 ,  0.12943923,
         0.20688672, -0.31905192, -0.08860896,  0.03574281, -0.08160941,
         0.18036625,  0.1580494 , -0.05106024, -0.33877605,  0.1649966 ,
         0.04474928,  0.01678991,  0.12369797, -0.07052709, -0.24740943,
         0.21356785,  0.17060143,  0.208817  , -0.38965434,  0.28148013,
        -0.1581764 ,  0.07469995,  0.18613012,  0.02442744,  0.21292958,
         0.10694063, -0.04253032, -0.02229722, -0.2377445 , -0.06346478,
        -0.1301896 ,  0.0448098 , -0.26745325,  0.36011165, -0.12510185,
         0.04434468,  0.04743296,  0.23341532,  0.34588403,  0.12469867,
         0.403762  ,  0.1786476 ,  0.05402811,  0.06891229,  0.4194087 ,
         0.26307368,  0.11896725, -0.23281762,  0.13456018, -0.10330726],
       dtype=float32),
 array([-0.22505139,  0.23939906,  0.03228942,  0.08651988,  0.10835537,
        -0.39909694,  0.11805752,  0.5843088 , -0.3601277 , -0.21018042,
        -0.0458467 , -0.37054536, -0.04955179,  0.02758927,  0.16196215,
        -0.06001304,  0.06928518, -0.31235597, -0.09246409, -0.58732367,
         0.04673076,  0.14917223,  0.20682368, -0.1586203 , -0.04826985,
         0.04201091, -0.31651288, -0.14687575, -0.22179164,  0.09525613,
         0.3218156 ,  0.03017014,  0.08426169, -0.13911647, -0.03350268,
         0.32818002, -0.03215081, -0.19279124, -0.12297397, -0.53735775,
         0.01958571, -0.20484008, -0.04703097,  0.04807471,  0.19498591,
        -0.05732471, -0.20460945, -0.06932336,  0.1369903 ,  0.11361659,
         0.2418475 , -0.40495002, -0.08207601,  0.05932181, -0.1399062 ,
         0.20642944,  0.18240175, -0.0609867 , -0.34659716,  0.22164303,
         0.04458843,  0.01703791,  0.14156112, -0.08222192, -0.28212863,
         0.2531331 ,  0.23576875,  0.2720504 , -0.4016545 ,  0.31520042,
        -0.17231847,  0.0246843 ,  0.19988051,  0.01885931,  0.26736814,
         0.11874342, -0.07011818,  0.00154099, -0.2659877 , -0.13157381,
        -0.14537764,  0.03923516, -0.30284676,  0.40860713, -0.12006088,
         0.09457888,  0.07841602,  0.23000945,  0.38880596,  0.12034738,
         0.46432316,  0.19529319,  0.03612697,  0.11457746,  0.4784982 ,
         0.2769469 ,  0.13881701, -0.32599315,  0.15554772, -0.11706846],
       dtype=float32),
 array([-0.2573401 ,  0.30323622,  0.04361198,  0.12218591,  0.10652817,
        -0.4690111 ,  0.19070789,  0.78136194, -0.45978355, -0.22614709,
        -0.08709432, -0.46311048, -0.05377913,  0.08752272,  0.2256674 ,
        -0.11082761,  0.03350465, -0.37629268, -0.12650006, -0.73705596,
         0.09437206,  0.14495732,  0.3172601 , -0.22317101, -0.0710691 ,
         0.07702934, -0.40456313, -0.21858594, -0.30296654,  0.07203882,
         0.3526903 ,  0.00452972,  0.14512585, -0.20653138, -0.01203028,
         0.38706514,  0.00229716, -0.24434921, -0.17672177, -0.6867308 ,
         0.0266793 , -0.27569714, -0.09313132,  0.08379918,  0.22914524,
        -0.10331804, -0.34111553, -0.112693  ,  0.22232172,  0.1973451 ,
         0.3073454 , -0.45750904, -0.15031311,  0.05214554, -0.1287235 ,
         0.24774389,  0.2467507 , -0.0639688 , -0.52075374,  0.24098532,
         0.06945406,  0.02221677,  0.18607844, -0.10918804, -0.36474672,
         0.32271245,  0.24052545,  0.30404952, -0.6001073 ,  0.41962054,
        -0.23813058,  0.13854143,  0.28475243,  0.0266821 ,  0.3164089 ,
         0.15418871, -0.04532942, -0.04135304, -0.3621959 , -0.08563076,
        -0.19561122,  0.0747393 , -0.39106628,  0.5293444 , -0.2023221 ,
         0.05300878,  0.0724384 ,  0.35847706,  0.5095797 ,  0.2014337 ,
         0.5918225 ,  0.2773154 ,  0.0920135 ,  0.09525859,  0.63947725,
         0.39071056,  0.19110356, -0.318919  ,  0.20402908, -0.15359959],
       dtype=float32),
 array([-2.15751231e-01,  2.48614892e-01,  3.76190841e-02,  9.60480198e-02,
         9.97969136e-02, -3.95730644e-01,  1.62036672e-01,  6.51848018e-01,
        -3.87716055e-01, -1.96505412e-01, -6.38496727e-02, -3.87008399e-01,
        -5.21465428e-02,  6.87069967e-02,  1.87777445e-01, -8.83709714e-02,
         3.48099656e-02, -3.17789912e-01, -1.09638281e-01, -6.22260988e-01,
         7.54775479e-02,  1.25926659e-01,  2.57691413e-01, -1.80392459e-01,
        -4.79633100e-02,  6.34339675e-02, -3.37542802e-01, -1.73532680e-01,
        -2.49628559e-01,  6.53940514e-02,  3.02971482e-01,  3.18130781e-03,
         1.12793386e-01, -1.78209856e-01, -9.33395606e-03,  3.38639826e-01,
        -3.38108308e-04, -1.97421864e-01, -1.50533274e-01, -5.73146164e-01,
         2.65978072e-02, -2.31118038e-01, -8.21349993e-02,  7.44475499e-02,
         1.98103949e-01, -7.96468630e-02, -2.76420325e-01, -9.37947854e-02,
         1.77984342e-01,  1.63200453e-01,  2.52563059e-01, -3.87698263e-01,
        -1.26543805e-01,  5.04779667e-02, -1.13491990e-01,  2.04296768e-01,
         2.08969727e-01, -5.98849803e-02, -4.23898578e-01,  2.02912107e-01,
         5.31950630e-02,  8.16404540e-03,  1.56522647e-01, -9.54478905e-02,
        -3.04190636e-01,  2.75662094e-01,  2.06587598e-01,  2.54324108e-01,
        -4.85127538e-01,  3.55255455e-01, -1.97623357e-01,  1.18626267e-01,
         2.33374298e-01,  2.17991546e-02,  2.68735915e-01,  1.29810065e-01,
        -3.25466432e-02, -3.46608348e-02, -3.01240355e-01, -8.14749599e-02,
        -1.66312099e-01,  6.46143481e-02, -3.27765554e-01,  4.35222268e-01,
        -1.64018586e-01,  5.00446856e-02,  6.79679811e-02,  2.92252719e-01,
         4.17741448e-01,  1.67979717e-01,  4.85025615e-01,  2.30704129e-01,
         7.16721043e-02,  8.58628154e-02,  5.30940950e-01,  3.24771315e-01,
         1.68128073e-01, -2.76037753e-01,  1.69328198e-01, -1.32387564e-01],
       dtype=float32),
 array([-0.23711255,  0.26774505,  0.03818038,  0.10672478,  0.1164716 ,
        -0.43716824,  0.16793765,  0.70242727, -0.41823974, -0.22144222,
        -0.06468122, -0.42047328, -0.05326953,  0.0666675 ,  0.20044404,
        -0.08749244,  0.04860344, -0.35140365, -0.11642379, -0.6756073 ,
         0.07463965,  0.14358068,  0.27457076, -0.19300142, -0.05078914,
         0.06052152, -0.3584327 , -0.18771173, -0.2726013 ,  0.08110432,
         0.34144655,  0.00781487,  0.12439672, -0.1916155 , -0.01810522,
         0.36940888, -0.0092098 , -0.21385294, -0.16428694, -0.62360764,
         0.02067536, -0.24390048, -0.08346213,  0.07488035,  0.21751605,
        -0.07948525, -0.28462753, -0.09588742,  0.18337914,  0.16549256,
         0.27545512, -0.42834222, -0.12809438,  0.05712486, -0.13402651,
         0.21814013,  0.21760783, -0.06670117, -0.44268018,  0.22902869,
         0.06067291,  0.01268157,  0.17459342, -0.10237431, -0.33571318,
         0.29821628,  0.23572375,  0.28529218, -0.51517576,  0.38522464,
        -0.20403154,  0.10696804,  0.2460704 ,  0.02210931,  0.29708716,
         0.13349973, -0.04147181, -0.02363368, -0.3224149 , -0.10598528,
        -0.18066342,  0.06657381, -0.35626104,  0.46787876, -0.17307022,
         0.06242404,  0.08087929,  0.30510604,  0.45566985,  0.1683898 ,
         0.5242033 ,  0.24541888,  0.07070984,  0.10234732,  0.56702894,
         0.34034792,  0.17190048, -0.31289163,  0.17837681, -0.13817286],
       dtype=float32),
 array([-0.23749116,  0.2698637 ,  0.04708111,  0.11483068,  0.10767675,
        -0.43597525,  0.18459383,  0.729653  , -0.42773598, -0.2162458 ,
        -0.06436601, -0.42584017, -0.0537859 ,  0.076107  ,  0.20811726,
        -0.08897618,  0.03977087, -0.3584204 , -0.12556008, -0.6958038 ,
         0.08437963,  0.13999553,  0.29586908, -0.20796612, -0.05578163,
         0.06877007, -0.36869353, -0.19715987, -0.28324533,  0.07312378,
         0.3359701 ,  0.00208875,  0.13597286, -0.2082286 , -0.01150959,
         0.36955357, -0.00098531, -0.2197247 , -0.1807908 , -0.64227545,
         0.02476803, -0.2555613 , -0.09483895,  0.08322964,  0.22578287,
        -0.0871248 , -0.30652833, -0.09985948,  0.20111619,  0.18051676,
         0.28162518, -0.42495698, -0.14545168,  0.05700405, -0.12892345,
         0.22131708,  0.22946785, -0.0658252 , -0.46590218,  0.22738147,
         0.06479183,  0.01255922,  0.18056461, -0.10563867, -0.3479412 ,
         0.31060928,  0.22672905,  0.2884685 , -0.54423827,  0.3966424 ,
        -0.21087857,  0.12826145,  0.260421  ,  0.0218154 ,  0.29769322,
         0.13519366, -0.03044152, -0.04139673, -0.3355917 , -0.09830642,
        -0.19094887,  0.07166042, -0.3694859 ,  0.48217878, -0.18599169,
         0.04739163,  0.07467091,  0.32750565,  0.46570134,  0.1864302 ,
         0.53793323,  0.25747806,  0.08356535,  0.09735186,  0.5901376 ,
         0.36242005,  0.18612956, -0.30253395,  0.18244627, -0.1464036 ],
       dtype=float32),
 array([-0.19599433,  0.22446948,  0.03113891,  0.08642952,  0.09519427,
        -0.3623469 ,  0.13653043,  0.5779113 , -0.34182125, -0.18404987,
        -0.03916116, -0.34471256, -0.0484202 ,  0.04130928,  0.15609214,
        -0.05596342,  0.05394527, -0.29428825, -0.09112941, -0.56214345,
         0.05311146,  0.12710269,  0.21916954, -0.15521276, -0.04851799,
         0.04331754, -0.29105175, -0.15457483, -0.22240764,  0.06951541,
         0.28320688,  0.01800295,  0.09705009, -0.16098207, -0.02017856,
         0.3037874 , -0.01325237, -0.18726203, -0.13242203, -0.51664925,
         0.01649311, -0.20052515, -0.05329979,  0.06352276,  0.19512445,
        -0.0583397 , -0.22478215, -0.06930251,  0.14881964,  0.1300171 ,
         0.22524314, -0.35771662, -0.10083741,  0.04550822, -0.1236451 ,
         0.17776118,  0.18360509, -0.05129841, -0.35365131,  0.19591925,
         0.04466252,  0.01150069,  0.13493176, -0.08293057, -0.27725905,
         0.24475908,  0.20008795,  0.25121984, -0.41017187,  0.31038958,
        -0.16456172,  0.06819271,  0.20318131,  0.02305923,  0.25353214,
         0.10759343, -0.04168943, -0.02024663, -0.26131874, -0.10038041,
        -0.14794432,  0.04914263, -0.28899685,  0.38306054, -0.13357237,
         0.06632283,  0.07056741,  0.24189645,  0.37349018,  0.13745321,
         0.43730292,  0.20330204,  0.05683285,  0.10285395,  0.46639973,
         0.28225616,  0.14092389, -0.2701326 ,  0.14244792, -0.11063377],
       dtype=float32),
 array([-0.23390417,  0.2481375 ,  0.03677519,  0.09581425,  0.11557323,
        -0.419437  ,  0.12249649,  0.62677634, -0.39523497, -0.21780503,
        -0.05010317, -0.3902808 , -0.05289676,  0.03836037,  0.17654242,
        -0.05611736,  0.07814756, -0.33219433, -0.10561807, -0.63093174,
         0.04761569,  0.16036306,  0.2335256 , -0.16536944, -0.04226886,
         0.0550267 , -0.3421655 , -0.16053376, -0.2445008 ,  0.09661905,
         0.33639997,  0.02859632,  0.09465191, -0.15307252, -0.03019575,
         0.34660912, -0.03952499, -0.21149056, -0.12284891, -0.5760201 ,
         0.01856289, -0.2234453 , -0.05037329,  0.0647762 ,  0.21191196,
        -0.06641146, -0.23561189, -0.07484324,  0.15367737,  0.1224677 ,
         0.24759865, -0.41760913, -0.09599026,  0.06840762, -0.14989072,
         0.20793399,  0.2015398 , -0.06102873, -0.37558287,  0.23449394,
         0.05296379,  0.01141962,  0.15706645, -0.08304347, -0.30630726,
         0.2702251 ,  0.24769077,  0.28681585, -0.43302053,  0.33987275,
        -0.1892606 ,  0.04004332,  0.2045705 ,  0.01238692,  0.28946912,
         0.12977973, -0.06322052,  0.00444017, -0.27587715, -0.14285494,
        -0.14197206,  0.05011274, -0.31623805,  0.43173704, -0.13511918,
         0.09239291,  0.08509833,  0.25889105,  0.41098887,  0.12346041,
         0.4961582 ,  0.21135417,  0.0442372 ,  0.12749663,  0.4987971 ,
         0.2998378 ,  0.15033618, -0.33327907,  0.16267614, -0.11140927],
       dtype=float32),
 array([-0.2519943 ,  0.2769872 ,  0.03250307,  0.10063899,  0.13159062,
        -0.46268052,  0.13916335,  0.68244725, -0.40837532, -0.249291  ,
        -0.0396557 , -0.43201703, -0.06352126,  0.025939  ,  0.18812746,
        -0.05627237,  0.08935908, -0.36319652, -0.1005235 , -0.68627024,
         0.0549641 ,  0.1670562 ,  0.23741631, -0.18209559, -0.06069995,
         0.04527291, -0.35504436, -0.17401281, -0.2565691 ,  0.10532968,
         0.37513825,  0.03740797,  0.09958135, -0.17173731, -0.03813714,
         0.3777526 , -0.03245272, -0.23042414, -0.14999455, -0.62538075,
         0.01805505, -0.24014111, -0.03844219,  0.06197288,  0.23977342,
        -0.07033934, -0.23138553, -0.06887941,  0.16596843,  0.13285902,
         0.2751665 , -0.46254554, -0.10064384,  0.06121495, -0.16469872,
         0.23483874,  0.21288574, -0.06874596, -0.3856446 ,  0.25195608,
         0.05043966,  0.01888908,  0.1643189 , -0.09119408, -0.33439073,
         0.29544848,  0.26579744,  0.32951754, -0.45738125,  0.36125985,
        -0.19328766,  0.0197075 ,  0.23148514,  0.02579041,  0.31626588,
         0.13459371, -0.07643835, -0.0066563 , -0.30795524, -0.1543519 ,
        -0.17173544,  0.04520953, -0.34791878,  0.47197846, -0.1326194 ,
         0.1135558 ,  0.10026008,  0.26978424,  0.46095312,  0.14090301,
         0.538519  ,  0.22882357,  0.04502515,  0.1509735 ,  0.5516201 ,
         0.32443187,  0.16001387, -0.37395462,  0.17112747, -0.14153396],
       dtype=float32),
 array([-2.11109862e-01,  2.37358123e-01,  3.59028317e-02,  9.41347331e-02,
         1.03290431e-01, -3.87948275e-01,  1.58262551e-01,  6.40345573e-01,
        -3.78986478e-01, -1.92621589e-01, -5.53988963e-02, -3.76190096e-01,
        -4.81806584e-02,  6.29854575e-02,  1.81201726e-01, -7.79847130e-02,
         3.84440757e-02, -3.15203726e-01, -1.09598905e-01, -6.12110496e-01,
         6.89380616e-02,  1.26840055e-01,  2.58738101e-01, -1.72588632e-01,
        -4.46063206e-02,  5.78784943e-02, -3.22830319e-01, -1.75060004e-01,
        -2.48967439e-01,  6.92991242e-02,  3.01064759e-01,  3.17708473e-04,
         1.15882002e-01, -1.76451340e-01, -1.14099989e-02,  3.28939229e-01,
        -5.01319440e-03, -1.92615032e-01, -1.48714334e-01, -5.64575434e-01,
         2.08338033e-02, -2.25356892e-01, -8.12115669e-02,  7.23647773e-02,
         1.95045352e-01, -7.21607432e-02, -2.65765756e-01, -9.26319808e-02,
         1.67022079e-01,  1.55218497e-01,  2.43593514e-01, -3.79557461e-01,
        -1.21425271e-01,  5.42038828e-02, -1.16869956e-01,  1.94859236e-01,
         2.03329131e-01, -5.98775335e-02, -4.08230096e-01,  2.04438627e-01,
         5.80420233e-02,  7.89259747e-03,  1.57382458e-01, -9.27155614e-02,
        -3.07159871e-01,  2.68991441e-01,  2.08859950e-01,  2.49783337e-01,
        -4.74955201e-01,  3.51948589e-01, -1.88558176e-01,  1.07161410e-01,
         2.22164959e-01,  1.82735156e-02,  2.65205920e-01,  1.19370222e-01,
        -3.00723538e-02, -2.38490198e-02, -2.97723055e-01, -9.13661420e-02,
        -1.59699619e-01,  6.52810857e-02, -3.19427937e-01,  4.21860009e-01,
        -1.65576518e-01,  5.15178330e-02,  6.88542351e-02,  2.83314675e-01,
         4.03502315e-01,  1.54563680e-01,  4.74199176e-01,  2.22687989e-01,
         7.15300515e-02,  8.97805020e-02,  5.18241465e-01,  3.11699033e-01,
         1.59793332e-01, -2.74208575e-01,  1.60815448e-01, -1.26050964e-01],
       dtype=float32),
 array([-0.2617619 ,  0.2766219 ,  0.04078227,  0.10315628,  0.13070896,
        -0.4611036 ,  0.14102842,  0.6808578 , -0.41933537, -0.24400268,
        -0.05500767, -0.42399108, -0.05771862,  0.03093111,  0.18860525,
        -0.06682014,  0.08321171, -0.36281204, -0.10769205, -0.6824581 ,
         0.05109255,  0.18061513,  0.24917048, -0.18072838, -0.0519092 ,
         0.04888172, -0.3692711 , -0.17383835, -0.2637261 ,  0.11089242,
         0.37178957,  0.03076115,  0.09822001, -0.16518952, -0.03790994,
         0.3844499 , -0.04185809, -0.22886926, -0.14095256, -0.6250055 ,
         0.02468899, -0.24413249, -0.05736458,  0.0611667 ,  0.2262357 ,
        -0.06689968, -0.23995686, -0.08524129,  0.15716402,  0.1290564 ,
         0.2788132 , -0.4717429 , -0.09235695,  0.07456546, -0.1699346 ,
         0.235022  ,  0.21094722, -0.07126166, -0.40568006,  0.25792944,
         0.0552738 ,  0.01462234,  0.16531973, -0.09452052, -0.32336837,
         0.29751375,  0.27455246,  0.3131923 , -0.46903768,  0.3708167 ,
        -0.19936143,  0.03744956,  0.23574975,  0.02090777,  0.31386143,
         0.1382789 , -0.08171809,  0.00483755, -0.31023   , -0.1575548 ,
        -0.1648764 ,  0.0441103 , -0.35165718,  0.473811  , -0.14364898,
         0.10854249,  0.09288558,  0.27031922,  0.4464597 ,  0.13665788,
         0.54188883,  0.2280372 ,  0.04173933,  0.13312468,  0.55486935,
         0.31911585,  0.16372576, -0.37994653,  0.181374  , -0.13547722],
       dtype=float32),
 array([-0.27795693,  0.2955072 ,  0.04105591,  0.10514176,  0.13702673,
        -0.49477994,  0.14877549,  0.72992915, -0.45278695, -0.2609879 ,
        -0.0531917 , -0.45766962, -0.06249413,  0.03196894,  0.19906157,
        -0.07209305,  0.09367695, -0.39188978, -0.11438623, -0.73403764,
         0.05544742,  0.19167349,  0.26014742, -0.19603571, -0.05947269,
         0.04951202, -0.3902031 , -0.18529148, -0.27999216,  0.11439415,
         0.39965463,  0.03462616,  0.10286666, -0.1813167 , -0.04516312,
         0.41339383, -0.04489138, -0.24702534, -0.15276639, -0.67440623,
         0.02526082, -0.258322  , -0.05432852,  0.06747828,  0.2530633 ,
        -0.07235601, -0.26020762, -0.08568062,  0.1674596 ,  0.13835175,
         0.29710665, -0.4997554 , -0.10226545,  0.0740285 , -0.18427807,
         0.24790603,  0.22702889, -0.07941145, -0.43151072,  0.27515772,
         0.05585276,  0.01875802,  0.1816551 , -0.1026289 , -0.34967044,
         0.3172678 ,  0.29351687,  0.3423159 , -0.5013954 ,  0.39189506,
        -0.21405137,  0.03133562,  0.2436789 ,  0.02090811,  0.34077114,
         0.14843182, -0.08329788,  0.00440154, -0.32669464, -0.1645286 ,
        -0.17500535,  0.05306153, -0.37708417,  0.5081178 , -0.15148005,

In [103]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.190334,0.215546,0.033876,0.084325,0.081461,-0.345515,0.131527,0.561290,-0.330890,-0.171352,...,0.426742,0.197938,0.058364,0.080643,0.452604,0.280698,0.136227,-0.246273,0.143816,-0.109621
1,-0.180804,0.202745,0.029607,0.077643,0.072470,-0.327818,0.114801,0.520338,-0.301364,-0.154203,...,0.403762,0.178648,0.054028,0.068912,0.419409,0.263074,0.118967,-0.232818,0.134560,-0.103307
2,-0.225051,0.239399,0.032289,0.086520,0.108355,-0.399097,0.118058,0.584309,-0.360128,-0.210180,...,0.464323,0.195293,0.036127,0.114577,0.478498,0.276947,0.138817,-0.325993,0.155548,-0.117068
3,-0.257340,0.303236,0.043612,0.122186,0.106528,-0.469011,0.190708,0.781362,-0.459784,-0.226147,...,0.591823,0.277315,0.092014,0.095259,0.639477,0.390711,0.191104,-0.318919,0.204029,-0.153600
4,-0.215751,0.248615,0.037619,0.096048,0.099797,-0.395731,0.162037,0.651848,-0.387716,-0.196505,...,0.485026,0.230704,0.071672,0.085863,0.530941,0.324771,0.168128,-0.276038,0.169328,-0.132388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.248369,0.277579,0.038062,0.105394,0.105868,-0.452295,0.152735,0.695773,-0.427645,-0.231803,...,0.535296,0.243774,0.067143,0.137401,0.556825,0.339139,0.168248,-0.341225,0.179368,-0.130415
5565,-0.240754,0.270620,0.040940,0.099786,0.122308,-0.428135,0.160949,0.684808,-0.413585,-0.214681,...,0.519640,0.230583,0.059619,0.084364,0.557943,0.334668,0.162829,-0.317714,0.176703,-0.130224
5566,-0.243477,0.285033,0.040706,0.117279,0.097365,-0.448065,0.193383,0.760881,-0.439760,-0.221090,...,0.558673,0.276215,0.098178,0.114644,0.611474,0.380657,0.189992,-0.300328,0.184355,-0.154703
5567,-0.229749,0.260019,0.038280,0.104464,0.104596,-0.422870,0.166905,0.688155,-0.404974,-0.214800,...,0.511538,0.243567,0.074104,0.103458,0.556153,0.339971,0.172165,-0.298487,0.175298,-0.138886
5568,-0.261274,0.289045,0.049335,0.126368,0.111356,-0.459901,0.188759,0.748689,-0.444575,-0.237427,...,0.569296,0.264205,0.089975,0.120468,0.612030,0.373571,0.191284,-0.335886,0.188709,-0.161505

In [83]:
df.shape

(5569, 100)

In [82]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.190334,0.215546,0.033876,0.084325,0.081461,-0.345515,0.131527,0.561290,-0.330890,-0.171352,...,0.426742,0.197938,0.058364,0.080643,0.452604,0.280698,0.136227,-0.246273,0.143816,-0.109621
1,-0.180804,0.202745,0.029607,0.077643,0.072470,-0.327818,0.114801,0.520338,-0.301364,-0.154203,...,0.403762,0.178648,0.054028,0.068912,0.419409,0.263074,0.118967,-0.232818,0.134560,-0.103307
2,-0.225051,0.239399,0.032289,0.086520,0.108355,-0.399097,0.118058,0.584309,-0.360128,-0.210180,...,0.464323,0.195293,0.036127,0.114577,0.478498,0.276947,0.138817,-0.325993,0.155548,-0.117068
3,-0.257340,0.303236,0.043612,0.122186,0.106528,-0.469011,0.190708,0.781362,-0.459784,-0.226147,...,0.591823,0.277315,0.092014,0.095259,0.639477,0.390711,0.191104,-0.318919,0.204029,-0.153600
4,-0.215751,0.248615,0.037619,0.096048,0.099797,-0.395731,0.162037,0.651848,-0.387716,-0.196505,...,0.485026,0.230704,0.071672,0.085863,0.530941,0.324771,0.168128,-0.276038,0.169328,-0.132388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.248369,0.277579,0.038062,0.105394,0.105868,-0.452295,0.152735,0.695773,-0.427645,-0.231803,...,0.535296,0.243774,0.067143,0.137401,0.556825,0.339139,0.168248,-0.341225,0.179368,-0.130415
5565,-0.240754,0.270620,0.040940,0.099786,0.122308,-0.428135,0.160949,0.684808,-0.413585,-0.214681,...,0.519640,0.230583,0.059619,0.084364,0.557943,0.334668,0.162829,-0.317714,0.176703,-0.130224
5566,-0.243477,0.285033,0.040706,0.117279,0.097365,-0.448065,0.193383,0.760881,-0.439760,-0.221090,...,0.558673,0.276215,0.098178,0.114644,0.611474,0.380657,0.189992,-0.300328,0.184355,-0.154703
5567,-0.229749,0.260019,0.038280,0.104464,0.104596,-0.422870,0.166905,0.688155,-0.404974,-0.214800,...,0.511538,0.243567,0.074104,0.103458,0.556153,0.339971,0.172165,-0.298487,0.175298,-0.138886
5568,-0.261274,0.289045,0.049335,0.126368,0.111356,-0.459901,0.188759,0.748689,-0.444575,-0.237427,...,0.569296,0.264205,0.089975,0.120468,0.612030,0.373571,0.191284,-0.335886,0.188709,-0.161505

In [86]:
df.isnull().sum()

0     12
1     12
2     12
3     12
4     12
      ..
95    12
96    12
97    12
98    12
99    12
Length: 100, dtype: int64

In [87]:
df.dropna(inplace=True)

In [88]:
df.shape

(5557, 100)

In [95]:
X_new=df

In [96]:
X_new.shape

(5557, 100)

In [98]:
y.shape

(5569,)

In [91]:
from sklearn.model_selection import train_test_split

In [97]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_new,y,test_size=0.20)

ValueError: Found input variables with inconsistent numbers of samples: [5557, 5569]